pagopa/selfcare-onboarding

- .identity/99_variables.tf
- .identity/mongodb.tf
- onboarding-functions/README.md
- onboarding-functions/pom.xml
- onboarding-functions/src/main/java/it/pagopa/selfcare/OnboardingFunctions.java
- onboarding-functions/src/main/java/it/pagopa/selfcare/entity/Onboarding.java
- onboarding-functions/src/main/java/it/pagopa/selfcare/entity/Token.java
- onboarding-functions/src/main/java/it/pagopa/selfcare/exception/ResourceNotFoundException.java
- onboarding-functions/src/main/java/it/pagopa/selfcare/repository/OnboardingRepository.java
- onboarding-functions/src/main/java/it/pagopa/selfcare/repository/TokenRepository.java
- onboarding-functions/src/main/java/it/pagopa/selfcare/service/ContractService.java
- onboarding-functions/src/main/java/it/pagopa/selfcare/service/ContractServiceDefault.java
- onboarding-functions/src/main/java/it/pagopa/selfcare/service/OnboardingService.java
- onboarding-functions/src/main/resources/application.properties
- onboarding-functions/src/test/java/it/pagopa/selfcare/service/ContractServiceDefaultTest.java
- onboarding-functions/src/test/java/it/pagopa/selfcare/service/OnboardingServiceTest.java
- onboarding-ms/src/main/java/it/pagopa/selfcare/entity/Onboarding.java
- onboarding-ms/src/main/java/it/pagopa/selfcare/service/OnboardingServiceDefault.java
- onboarding-ms/src/main/resources/application.properties
- onboarding-sdk/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/OnboardingStatus.java
* Moved definition database and collection 'onboarding' from selfcare-infra to identity folder. In addition, added definition of new collection token.
* Implemented step "SaveToken" for onboarding async workflow
* Added expiring-date on onboarding, it indicates when an onboarding will expire before consumed
* Update README
Onboarding async workflow include as second step saving token that contain information about the contract that will be sended to institution. It retrieves contract from storage, calculate digest and saving information in a collection 'tokens' on mongodb.
> [SELC-3157] feat: SaveToken step for onboarding async

- README.md
- onboarding-sdk/onboarding-sdk-azure-storage/README.md
- onboarding-sdk/onboarding-sdk-common/README.md
- onboarding-sdk/onboarding-sdk-product/README.md
- onboarding-sdk/onboarding-sdk-product/src/main/schema/Product_v1.avsc
Added REAME to onboarding parent
Added REAME to onboarding sdk
Update documentation about onboarding-sdk
> README onboarding-sdk

- .github/workflows/code_review.yml
- onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/OnboardingControllerIT.java
Fix validateProductRole on check if roles is exactly one.
Replacing selfcare-commons with onboarding-sdk-common has introduced a bug in validateProductRole when an onboarding are submitted.
> fix: check validateProductRole if roles is exactly one

- .github/workflows/release_onboarding_sdk.yml
- onboarding-sdk/onboarding-sdk-azure-storage/pom.xml
- onboarding-sdk/onboarding-sdk-common/pom.xml
- onboarding-sdk/onboarding-sdk-product/README.md
- onboarding-sdk/onboarding-sdk-product/pom.xml
- onboarding-sdk/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductService.java
- onboarding-sdk/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceDefault.java
- onboarding-sdk/onboarding-sdk-product/src/test/java/ProductServiceDefaultTest.java
- onboarding-sdk/pom.xml
* Refactor ProductServiceDefault for reducing code and adding java doc
* Set Java 17
* Update README
* Refactor release workflow for only deploy version
ProductServiceDefault miss about documentation on single method so it is difficult for developer know what expected from its method. API should have documentation for improving usage of developer. 
Java 11 will be not supported soon for Selfcare so Java 17 is also the new minimum version for SDK.
> Refactor onboarding-sdk-product setting java 17

- .github/workflows/check_pr.yml
- .github/workflows/code_review_functions.yml
- .github/workflows/code_review_libs.yml
- .github/workflows/code_review_ms.yml
- .github/workflows/deploy_onboarding_functions.yml
- .github/workflows/release_onboarding_sdk.yml
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
1. Implemented the use of the **s4u/setup-maven-action** action in the GitHub workflows.
2. Set the Maven version to **3.9.5**.
3. Enabled Maven cache to reduce the execution time of the workflows significantly.
4. Fix onboarding-ms unit test
The entire repository is set up to perform builds using Maven with version **3.9.x.** In the current GitHub workflows, using the setup-java action alone results in the use of an older version of Maven. This change is required to ensure that the workflows use the correct Maven version (**3.9.x**), aligning with the repository's setup. Additionally, the use of Maven cache is crucial for significantly reducing the execution time of the workflows by caching the Java libraries.
> ops: using cache and 3.9.5 version about maven on workflow

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/OnboardingCompletionFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/OnboardingCompletionFunctionsTest.java
1. **Creation of a Trigger for Starting Asynchronous Onboarding Completion Activities**: Implemented the trigger mechanism designed to initiate the asynchronous processes necessary for completing the onboarding.
2. **Development Azure Functions for Business Logic Execution**: Each function is responsible for carrying out a specific part of the onboarding completion process, in the next PRs will be implemented the business logic related. 
Completing an onboarding ends with a series of asynchronous operations performed by some azure functions. These activities consist of creating the institution, creating onboarding with its associated users and sending the onboarding confirmation email to the institution
> [SELC-3452] feat: completion async orchestration

- apps/onboarding-ms/pom.xml
Added quarkus-smallrye-health, importing the smallrye-health extension directly exposes three REST endpoints:
/q/health/live - The application is up and running.
/q/health/ready - The application is ready to serve requests.
/q/health/started - The application is started.
/q/health - Accumulating all health check procedures in the application.
We want provide information about onboarding-ms state to external viewers which is typically useful in cloud environments where automated processes must be able to determine whether the application should be discarded or restarted.
> ops: add smallrye-health

- .functions/onboarding-functions/env/dev/terraform.tfvars
- .functions/onboarding-functions/env/uat/terraform.tfvars
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
* Set onboardingId as reference at confirmation and rejection link when sending mail
* Fix user name and surname in contract
* Added dev and uat environment variables
This modification is crucial for the onboarding process. Previously, the completion email contained a link with a token reference, which was not as direct or specific as needed. By switching to an Onboarding entity reference, the link now directly relates to the specific onboarding request, improving the process's efficiency and user experience. This change ensures that upon successful onboarding requests, the email sent to the entity or admin contains a more relevant and accurate link for completing the onboarding process, directly tied to the Onboarding collection record.
> [SELC-2862] fix: onboarding confirmation and reject by onboardingId

- .container_apps/onboarding-ms/env/dev/terraform.tfvars
- .container_apps/onboarding-ms/env/prod/terraform.tfvars
- .container_apps/onboarding-ms/env/uat/terraform.tfvars
- apps/onboarding-ms/README.md
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/constants/CustomError.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/exception/ResourceNotFoundException.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/openapi/party_registry_proxy.json
- apps/onboarding-ms/src/main/resources/application.properties
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
retrieve and add parentDescription to onboarding Institution if it is AOO or UO
when onboarding AOO and UO we have to persist also parent description
run in debug mode, call api to onboarding PA and check in onboarding institution data to persist, parentDescription field
> [SELC-3483] Feat: retrieve and add parentDescription for AOO and UO onboardings

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/CommonFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingCompletionFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/SaveOnboardingStatusInput.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/OnboardingCompletionFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/OnboardingFunctionsTest.java
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
1. Using 0.1.3 onboarding-sdk 
2. Introduce common azure function for saving onboarding status, it is called at the end for each workflow
3. Save status REQUEST at first step of onboarding
3. Save status PENDING at the end of onboarding functions
3. Save status COMPLETED at the end of onboarding completion functions
Implementation of onboarding-ms and onboarding-functions about this [PR](https://github.com/pagopa/selfcare-onboarding/pull/64)
> [SELC-3504] feat: saving onboarding status

- .container_apps/onboarding-ms/env/dev/terraform.tfvars
- .container_apps/onboarding-ms/env/prod/terraform.tfvars
- .container_apps/onboarding-ms/env/uat/terraform.tfvars
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/openapi/onboarding_functions.json
- apps/onboarding-ms/src/main/resources/application.properties
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
* Added **start-completion-functions-api-key** as secret
* Fix ONBOARDING_FUNCTIONS_URL env value
* Change retrieving product as Uni avoiding thread blocked if it takes a lot of time
* Added rest api call to execute onboarding completion process async.
Start of orchestration described at this [PR](https://github.com/pagopa/selfcare-onboarding/pull/58). It is the last operation executed by completion onboarding process sync.
> [SELC-3452] feat: start async onboarding completion

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/OnboardingStatus.java
- Added new API for Onboarding logical deletion. 
- Added new Onboarding Status DELETED
A new API is required for logical deletion of onboarding, by updating the status to DELETED
tested in dev mode.
Called new API with 3 cases:
- Valid OnboardingId to update -> 204, status updated
- OnboardingId with wrong format -->  INVALID REQUEST with custom message
- OnboardingId already DELETED or NOT_FOUND --> INVALID REQUEST with custom message
- OnboardingId already NOT_FOUND --> INVALID REQUEST with custom message
> [SELC-2865] Feat: added new API for delete Onboarding

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
Update persist onboarding step sending also contractPath and onboardingId
When persist an onboarding, ms-core send notification to queue with institution and onboarding data. ContractPath and onboardingId are needed about notification.
> [SELC-3506] feat: persist sending contract path and id

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/ContractRequestResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/OnboardingGet.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/OnboardingGetResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/OnboardingImportContractResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/SortEnum.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Added API for get Onboarding with optional filters and pagination
An API is needed to retrieve onboardings
tested in dev mode.
Called new API with single, multiple or none filters, and with different pageNumber and pageSize.
> [SELC-2864] Feat: added API for get Onboarding with optional filters

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
* Added functionality for saving the path of the signed contract in the attribute '_contractSigned_'.
* Modified the 'persistOnboarding' call to 'ms-core' to include the 'contractSigned' attribute.
This change is required to enhance the onboarding process by ensuring that the path of the signed and validated contract is stored and subsequently sent to 'ms-core' for persistence. This addition will allow the path to be included in the event queue.
> feat: save and persist contract signed path when onboarding

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/PurgeConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/CommonFunctions.java
- apps/onboarding-functions/src/main/resources/application.properties
* Added two scheduled functions for executing purge history based on start and end dates.
* The '**PurgeInstancesCompleted**' function performs the purge of only COMPLETED workflows with a static schedule at 11 AM daily.
* The '**PurgeInstancesAll**' function performs the purge of all workflows with a static schedule at 12 PM daily.
* Added configuration for the start and end dates of the two functions, currently set to 60 to 30 days and 150 to 120 days respectively.
Azure Durable Functions used for executing workflows save metadata on Azure storage. If not appropriately purged, these data can accumulate, unnecessarily filling the storage and consuming resources. To address this, Azure provides APIs for purging the history of Durable Functions. The changes introduced in this pull request …
> [SELC-3577] feat: functions for purge durable history table

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Refactor PUT endpoint /deleted with /reject. DELETED is not used in onboarding lifecycle so this endpoint is designed to reject the data provided during the onboarding process. 
It is used during admin approval phase if the admin does not want to approve the onboarding request
> [SELC-3493] feat: Reject Endpoint for Enhanced Onboarding Process Approval

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForApprove.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForApprovePt.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/OnboardingFunctionsTest.java
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/OnboardingStatus.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- pom.xml
- test-coverage/pom.xml
replace TO_BE_VALIDATED to TOBEVALIDATED
The right onboarding status is TOBEVALIDATED
> fix: replace status TO_BE_VALIDATED to TOBEVALIDATED

- .github/workflows/call_release_function.yml
- .github/workflows/pr_functions.yml
- .github/workflows/pr_ms.yml
- .github/workflows/release_functions.yml
Reusable workflow to deploy the function
Get the environment from the current branch
Adopting GitHub flow
> [EC-97] Adapt function deployment pipeline to GitHub flow

- .github/workflows/call_release_ms.yml
- .github/workflows/release_ms.yml
- .identity/github_environment_cd.tf
- infra/container_apps/onboarding-ms/.terraform.lock.hcl
- infra/container_apps/onboarding-ms/container_app.tf
- infra/container_apps/onboarding-ms/main.tf
- infra/container_apps/onboarding-ms/private_dns.tf
- infra/container_apps/onboarding-ms/variables.tf
Reusable workflow to deploy the ms
Get the environment from the current branch
Very misc minor changes to container app TF module
Adopting GitHub flow
> [EC-98] Adapt ms deployment pipeline to GitHub flow

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
Added logging onboardingsOrchestrator function
It need for troubleshooting when function fails
> [SELC-2865] fix: add logging onboardingsOrchestrator function

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
Try only TaskFailedException.
The orchestrator can be blocked and waiting for new inputs and some throwables should never be caught by user code. It is important to try only TaskFailedException for user scope.
> [SELC-3580] fix: try only TaskFailedException

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductService.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceCacheable.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceDefault.java
- libs/onboarding-sdk-product/src/test/java/ProductServiceDefaultTest.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/service/ProductServiceCacheableTest.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/service/ProductServiceDefaultTest.java
- test-coverage/pom.xml
- Added method to validate a productRole given productId a Role
Check of productRole given productId and Role is required for API business logic when work with product
> [SELC-3962] Added method to validate a productRole given productId a Role

- .github/workflows/call_code_review.yml
- .github/workflows/pr_functions.yml
- .github/workflows/pr_libs.yml
- .github/workflows/pr_ms.yml
Added module as input on code review workflow
PR workflow can reuse code review workflow adding reference to module where review must be processed
> ops: module input on code review workflow

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/conf/TrustedListsCertificateSourceConfig.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingPgRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/onboarding-ms/src/test/resources/application.properties
* Added endpoint POST for onboarding PG institution /pg/completion with CONFIRMATION workflow
* Move transaction close before calling endpoint orchestration, it is necessary for handle sync response from orchestration function 
* TrustedListsCertificateSource refresh list based on signature enabled, in pnpg signature will be disabled
Implementation of PNPG onboarding use case where response must be sync. Sync response was already implemented but some bug because transaction of persisting onboarding was closed after calling orchestration. This caused onboarding not found when orchestration performed the find on start of the orchestration.
> [SELC-3996] feat: PNPG onboarding use case

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/UserRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/OnboardingResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/UserOnboardingResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/User.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtilsTest.java
* Refactor retrieve and saving user when onboarding, productRole missed
* Limit onboarding response removing taxcode and mail
ProductRole was not being saved during the onboarding request
> fix: save product role when onboarding

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/Product.java
- test-coverage/pom.xml
Added to Product configuration "testEnvProductIds" attribute, it is used for onboarding others product when current product is onboarded
A common use case is when we want to onboard for certain product also the test environment, for example for prod-interop we also onboard prod-interop-coll
> [SELC-4041] feat: product config for having test environment

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorConfirmation.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorContractRegistration.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForApprove.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForApprovePt.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
* Added business logic for onboarding test environment products configured using this [PR](https://github.com/pagopa/selfcare-onboarding/pull/143) when current product is onboarded
* Remove SEND_MAIL_CONFIRMATION_ACTIVITY function
A common use case is when we want to onboard for certain product also the test environment, for example for prod-interop we also onboard prod-interop-coll. This logic will replace the [onboarding interceptor](https://github.com/pagopa/selfcare-ms-onboarding-interceptor) behaviour and it will be dismissed
> [SELC-4041] feat: onboarding test environment products configured by testEnvProductIds

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
Added upperCase to recipientCode field into OnboardingMapper
This change is necessary to format recipientCode to SAP specification
> [SELC-4079] feat: added upperCase method to recipientCode field into OnboardingMapper

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/User.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/User.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/UserMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
User's mail on onboarding request is stored as uuid present on workContracts in PDV and in onboarding request.
> [SELC-4182] feat: mail stored in PDV workContract as UUID

- .github/workflows/release_functions.yml
- .github/workflows/release_ms.yml
- .github/workflows/release_pnpg_functions.yml
- .github/workflows/release_pnpg_ms.yml
Prod workflow on ms and functions must be trigger manually selecting prod environment
Every time a new release is created pipeline of uat and prod have been trigged. You have to approve or not for complete or reject their elaboration causing a lot of manually operation.
> ops: disable automation pipeline for prod environment

- .github/workflows/create_release_branch.yml
- .github/workflows/release_container_apps_infra.yml
- .github/workflows/release_container_apps_pnpg_infra.yml
- .github/workflows/release_functions_infra.yml
- .github/workflows/release_mongo_infra.yml
- .github/workflows/release_mongo_pnpg_infra.yml
* Added release mongo infra for PNPG
* Added trigger for PNPG infra when create a release branch
* Set manually release for prod environment
PNPG environment misses mongo infra pipeline and others pipeline were not triggered when a create release branch was executed. 
In addition, I disable automatic release for prod environment because deployment in uat and prod env includes a lot of manual operations (for ex. approve) so we want that uat release is less expensive in this term
> [SELC-4056] ops: pnpg pipeline and release manually in prod

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingImportContract.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Update field createdAt to LocalDateTime in ContractImported
This change has been implemented to align request's objects to codegen plugin and its setting to manage date fields as LocalDateTime
> [SELC-3982] fix: update field createdAt to LocalDateTime in ImportedContract

- .github/workflows/create_release_branch.yml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/OnboardingFunctionConfig.java
- apps/onboarding-functions/src/main/resources/application.properties
* Decrease read timeout of pdv rest client, it permits a fast retry azure functions in case of failures
* Enable startup of mongo client also for functions
We observe some exceptional timeout errors on pdv rest client. Having 60sec to throw timeout exception delay retry of azure functions
> ops: decrease pdv client timeout

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
* Return internal server error if orchestration metadata has status FAILED
* Fix some prod env valued
In PNPG use case onboarding process must fail returning internal server error if some errors happen
> fix: orchestration sync return internal server error

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
* Saving activatedAt on import workflow
* Sending activatedAt on import workflow when persist onboarding
* Set billing data on import workflow
> hotfix: sending activatedAt on import workflow when persist onboarding

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/ReasonRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/OnboardingGet.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- Added new ReasonRequest Object with reasonForReject attribute
- A new method has been added so that when the onboarding request is rejected by the PagoPA operator, in addition to changing the status, the new reasonForReject field is saved on the DB Entity
This change allows you to also inform via PEC the reason why your request was rejected by the PagoPA operator
the API was invoked locally and it was verified that the status was updated from TOBEVALIDATE to REJECTED and it was also verified that the new reasonForReject attribute was saved.
> [SELC - 4393]feat: implemented new method for onboarding reject API

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
added updatedAt in query to update
on the functions side this operation is not performed for reject. In a logical sense it is correct to modify the updatedAt when the request is rejected and not when the email is sent to the institution (function)
The microservice was started locally and the Reject API was invoked
> [SELC - 4393] fix: added updatedAt in query to update

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorContractRegistration.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForApprove.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- removed file attachment to mail (contract) during onboarding phase
- Renaming all methods and variables that contained "withContract" to "forContract"
This change was necessary because the onboarding flow has changed and now the contract will be downloaded from a dedicated FE page and will no longer be sent as an attachment in the PEC that reaches the institution
Once the flow was modified, the function was invoked and it was verified that the file was not attached via email
> [SELC - 4353] feat: removed file attachment to mail (contract) during onboarding phase

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
Added feature flag for persist user function
In order to distribute onboarding-ms indipendently from other microservices invoked, a feature flag has been added to invoke user-ms and persist user during onboarding phase. The default value has been set false.
I have run the CREATE_USERS function locally and checked the scenario.
> [SELC-4697] feat: added feature flag for persist user function

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
added originId in Institution in onboarding-functions, and a check in PdfMapper to assign a value to originId depending on taxCode presence
It is necessary to add the originId field and map it to the ivassCode for onboarding foreign insurance in the objects used by the onboarding API
> SELC-4709 fix: added originId in Institution in onboarding-functions

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
modified invocation to getInstitutions API to work with origin and originId when taxCode is not present
When creating an institution in the onboarding finalization phase there is a verification of the institution's existence by invoking a core api using taxCode and subunitCode. With this modification, the origin and originId can also be sent to the api to perform the verification in the absence of taxCode
> [SELC-4719] feat: Modified invocation to getInstitutions API to work with origin and originId when taxCode is not present

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
changed check on taxCode null in getInstitutions method
improved check using StringUtils.isNotBlank to handle taxCode empty
> SELC-4686 fix: changed check on taxCode null in getInstitutions method

- infra/container_apps/onboarding-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
… url
* Remove https to container app url
* Remove suffix {env}.westeurope.azurecontainerapps.io to container app url
You can call other container apps in the same environment from your application code using the container app name, for instance http://<APP_NAME> for internal requests. It is the best method for internal requests inside a Container App environment
> chore: Use Container App name as url when calling a container app

- apps/onboarding-cdc/Dockerfile
- added dockerfile to onboarding cdc module
> [SELC - 4960] feat: added Dockerfile to onboarding cdc

- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/mapper/OnboardingMapper.java
- apps/onboarding-cdc/src/main/resources/application.properties
- infra/container_apps/onboarding-cdc/env/dev-pnpg/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/dev/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/prod/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/uat/terraform.tfvars
> [SELC-5014] feat: Added terraform variables

- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/NotificationService.java
- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/OnboardingCdcService.java
- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/entity/util/QueueEvent.java
- apps/onboarding-cdc/src/main/openapi/onboarding_functions.json
- apps/onboarding-cdc/src/main/resources/application.properties
- apps/onboarding-cdc/src/test/java/it/pagopa/selfcare/onboarding/event/NotificationServiceTest.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/NotificationFunctions.java
- infra/container_apps/onboarding-cdc/env/dev/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/prod/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/uat/terraform.tfvars
Added logic to discriminate event type in cdc module before invoking function to send notifications
With this feature we have the ability to understand if the result of a change in an onboarding document we need to send an event on ADD or UPDATE on queues
local env
> [SELC-5034] feature: added logic to discriminate event type in cdc module

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/NotificationBuilder.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/StandardNotificationBuilder.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/FdNotificationBuilderTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/SapNotificationBuilderTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/StandardNotificationBuilderTest.java
Removed filePath from base builder and added only in standard builder
the node "filePath" in root model NotificationToSend should not have value for SAP and FD model
dev env
> [SELC-4894] fix: removed filePath from base builder and added only in standard builder

- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/NotificationService.java
- apps/onboarding-cdc/src/test/java/it/pagopa/selfcare/onboarding/event/NotificationServiceTest.java
- apps/onboarding-cdc/src/test/java/it/pagopa/selfcare/onboarding/event/profile/NotificationTestProfile.java
- apps/onboarding-cdc/src/test/resources/application.properties
- infra/container_apps/onboarding-cdc/env/prod/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/uat/terraform.tfvars
Added watch config to prevent azure function invocation on demand
With this feature we can disable the invocation of azure function.
local env
> SELC-5119 feat: added watch config to prevent azure function invocation on demand

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- added API to save the onboarding request from an Aggregator
- added check if isAggregator is TRUE to set workflowType to CONTRACT_REGISTRATION_AGGREGATOR
The endpoint dedicated to aggregation will take care of:
- Validate the product and verify that the aggregator does not already have an active membership for that product. The same check is NOT done for all the aggregated entities as in the case of membership already present this is not modified.
- Validate the data referring to the institution as already foreseen for classic onboarding
- Persist onboarding and launch Request to Join orchestration
The new API was invoked and it was verified that the data was correctly saved in the DB
> [SELC - 5065] feat: Added API to save the onboarding request from an Aggregator

- apps/onboarding-cdc/src/main/openapi/onboarding_functions.json
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/AggregateInstitutionRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingBaseRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/src/main/openapi/onboarding_functions.json
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Added :
- AggregateInstitution (ms)
- AggregateInstitutionRequest
- AggregateInstitution (function)
- updated function openapi to ms and cdc
This change was necessary because during the testing and integration phase with the BFF we realized that some attributes were required in the normal flow and in the case of Aggregator these attributes are not needed
> [SELC - 5148] feat: added new AggregateInstitution Object

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/FDConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/NotificationFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CheckOrganizationService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CheckOrganizationServiceDefault.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/TestUtils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/NotificationFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CheckOrganizationServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/profile/CheckOrganizationByPassTestProfile.java
- apps/onboarding-functions/src/test/resources/application.properties
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
added function for checkOrganization
Moving checkOrganization from selfcare-ms-external-interceptor in dedicated http function.
At the moment the function returns true, because we need to add the invocation to FD service.
local env
> SELC-4901: added function for checkOrganization

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
added check on null values of Token in BaseNotificationBuilder
There was a problem when building notification when the token entity didn't have contractSigned field
local env
> fix: added check on null values of Token in BaseNotificationBuilder

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefaultTest.java
Added function to check if onboarding should send notification, based on workflow type of onboarding
We need to send notifications only for onboarding of institution, ignoring onboarding of users and aggregates
local env
> [SELC-5191] feat: added function to check if onboarding should send notification

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
added query condition to retrieve only institution onboarding
The condition is necessary to recover only onboarding related to single institution onboarding. Thus discarding all onboardings of administrators (users) and aggregated institutions
local env
> [SELC-5073] fix: added query condition to retrieve only institution onboarding

- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/InstitutionResponse.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Added originId into response of get Onboardings by filters API
This field is necessary into addition administration flow from dashboard, where from this response and from originId and origin attributes the entire process is started
I have startet the microservice locally and tested the specific API
> [SELC-4371] fix: Added originId into response of get Onboardings by filters API

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/MailTemplatePlaceholdersConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/OnboardingWorkflowUser.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- apps/onboarding-functions/src/test/resources/application.properties
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- Added previousManagerId as attribute of Onboarding in order to detect email template
- Added previous manager name and previous manager surname into registration email in case of workflow USERS
In order to display name and surname of previous manager in case of addition administration flow, a new attribute has been added into Onboarding class. This attribute stores the previous manager identifier and it's used to compare current manager id with old one
I have deployed the feature branch in dev and tested the entire process of onboarding for workflowType USERS
> [SELC-5214] feat: Added previousManagerId as attribute of Onboarding in order to detect email template

- apps/onboarding-cdc/pom.xml
- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/InstitutionPaSubunitType.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
Adding EC as SubunitType as retro compatibility error due to some onboarding on db contains this value
Unit test
> Add subunittype EC

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/client/auth/EventhubSasTokenAuthorization.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/client/eventhub/EventHubRestClient.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/OnboardingFunctionConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/NotificationFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefault.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest2.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefaultTest.java
- apps/onboarding-functions/src/test/resources/application.properties
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- infra/container_apps/hub_spid_login/container_app.tf
- infra/container_apps/hub_spid_login/env/dev/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/dev/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/prod/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/uat/terraform.tfvars
- infra/container_apps/onboarding-cdc/main.tf
- infra/container_apps/onboarding-ms/container_app.tf
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/dev-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
- infra/functions/onboarding-functions/functions.tf
Adding new telemetry client when send new notification event to eventhub queue.
Currently onboarding does not monitor when send notification failure.
> [SELC-5290] Add monitoring for notification events

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
Added step to persist activatedAt for onboarding with workflowType USERS
For workflowType USERS, the field activatedAt was not filled during onboarding's completion
I have deployed the feature branch in DEV and completed the entire process of onboarding for a new institution
> [SELC-5284] fix: Added step to persist activatedAt for onboarding with workflowType USERS

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/constants/CustomError.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtilsTest.java
Added check on recipient Code. In particular:
- UO is retrieved by recipientCode from registry
- the ipa code of this UO is compared with originId into request of onboarding
- In case they are different, an exception is thrown with a specific error (DENIED_NO_ASSOCIATION)
- In case they are equals, but the retrieved UO has not taxCodeInvoicing, an exception is thrown with a specific error (DENIED_NO_BILLING)
> [SELC-5276] feat: Added check on recipient Code

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
updated query to retrieve onboarding to resend even without workflowType
The query didn't retrieve the onboardings without the workflowType attribute (which are the onboarding created by the old microservice)
local env
> [SELC-5299] fix: updated query to retrieve onboarding to resend even without workflowType

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Throw exception in of 404 for getUOFromRecipientCode
In case registry proxy returns 404 for getUO from recipient code, a ResourceNotFoundException is thrown
> [SELC-5276] fix: Throw exception in of 404 for getUOFromRecipientCode

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/client/auth/AuthenticationPropagationHeadersFactory.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/JwtSessionServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/client/auth/AuthenticationPropagationHeadersFactoryTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/JwtSessionServiceDefaultTest.java
Added condition to avoid error in CREATE_USERS function in case of 404 from PDV service. In this case, the bearer token of API request to user-ms is built by env variable.
When workflowType is IMPORT, the field userRequestUuid of onboarding is mocked. In order to manage the 404 from pdv, a new check has been added
I have deployed the feature branch in dev and tested the completion of entire process of onboarding
> [SELC-5322] feat: added check to avoid error in case of 404 for pdv

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- Added condition to check if user exists in PDV for api check-manager. If not, the method returns false
In order to not get a 5xx error code, in case the user sent into request does not exist, the API will return false
I have run ms locally and tested the api for every scenario
> [SELC-5400] fix: Added check on getUserFromPdv for check manager API

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
* Added: Manual assignment of operationId for each API operation in the OpenAPI specification.
* Updated the OpenAPI generation process to ensure that operationId is explicitly set for all operations.
This PR addresses the issue where operationId was missing in the automatically generated OpenAPI documentation by Quarkus. By default, Quarkus does not automatically set the operationId in the OpenAPI specification. This can lead to difficulties when integrating with API clients or tools that rely on operationId for method names or routing.
> chore: Add operationId to OpenAPI Documentation

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/SapNotificationBuilder.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/SapNotificationBuilderTest.java
Remove all try catch to avoid sent notification without all mandatory fields.
> [SELC-5423] Refactor notification

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtilsTest.java
Added check for EC recipient code in case of AOO/UO onboarding
In case of AOO/UO onbaording, there is no need to throw an exception if recipentCode is equal to UO subunitCode and this UO is part of EC hierarchy. 
I have deployed the microservice locally and tested the onboarding process for both case, AOO and UO
> [SELC-5384] fix: added check for EC recipient code in case of AOO/UO onboarding

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtilsTest.java
- added field istatCode into onboarding, retrieving value from proxy registry
- Refactor logic of additional checks on onboarding data
I have deployed the feature branch in DEV and tested the different scenario:
- AOO onboarding
- UO onboarding
- EC onboarding
> [SELC-5420] feat: added field istatCode into onboarding

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefault.java
Retrieve PDF could take long time so this method must run on Executor. As-is signature is malformed because the running are executed when the Uni is created and not when is called.
> fix: transform getting PDF as lambda for running on executor

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/OnboardingMapperTest.java
- Added user mapping for aggregate users
In the case of aggregator entities, for the users of the aggregated entities, it is necessary to map, if present, those related to the aggregated entity; otherwise, those of the aggregator.
> [SELC-5476] Feat: Added user mapping for aggregate users

- apps/onboarding-cdc/pom.xml
- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- libs/onboarding-sdk-product/pom.xml
Set onboarding-sdk dependencies version on apps module guarantee that also these versions are upgraded when perform set: versions on maven
This PR aims to force to use the last version of onboarding-sdk on entire project. This fix an issue that occurs when sdk upgrade the version and apps don't use this last version. The error happen during deploy when Docker image are builded.
> refactor: standardize using onboarding-sdk-version on entire project

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/AggregateInstitutionRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- Modified onboardingPaAggregation to persist also vatNumber given from csv
For the contract of the aggregating entities, it is necessary to include all the data of the aggregated entities, both those retrieved from IPA and those sent via CSV and not overwritten by IPA. Therefore, it is essential that all this data is available during the initial persistence.
> [SELC-5669] Feat: Modified onboardingPaAggregation to persist also vatNumber given from csv

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/pom.xml
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/Product.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceDefault.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/utils/ProductUtils.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/utils/ProductUtilsTest.java
- test-coverage/pom.xml
* **Default Role Mappings**: Retained existing default Product Roles in the roleMappings section.
* **Institution-Specific Role Mappings**: Added a new roleMappingsByInstitutionType section to define alternative Product Roles for specific InstitutionTypes.
This pull request introduces a new configuration option to associate Product Roles based on the InstitutionType. This enhancement allows for more granular role management, enabling different roles for specific types of institutions while maintaining default roles for others.
> [SELC-5629] feat: Associate Product Roles by InstitutionType

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductService.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceCacheable.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceDefault.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/service/ProductServiceCacheableTest.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/service/ProductServiceDefaultTest.java
- test-coverage/pom.xml
This new method is useful when you want to retrieve some description for a lot of products in the same instant. In this case, calling azure storage is useless because the configuration can't be change in one instant.
> [SELC-5632] feat: added getProductRaw on product-sdk to retrieve data without refreshing configuration

- .github/workflows/pr_libs.yml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/Product.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/ProductRole.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/ProductRoleInfo.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/entity/ProductTest.java
Fix getAllRoleMappings method
overlapping keys causes replace of roleMappings productRole association. This PR fix this issue maintain both productRoles list
> [SELC-5629] fix: getAllRoleMappings sdk when both maps are non-null with overlapping keys

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/GenericError.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- modify method generateAggregatesCsv to include prod-pagopa
- add pagopa fields in AggregateInstitution
- add unit test
It was tested by running the branch locally and invoking Onboarding Orchestrator with the following scenarios:
- onboarding with status REQUEST, productId = "prod-io"
- onboarding with status REQUEST, productId = "prod-pagopa"
- onboarding with status REQUEST, productId = "prod-pn"
- onboarding with status REQUEST, productId not equal to "prod-io", "prod-pagopa", "prod-pn"
> [SELC-5733] feat: create aggregates csv for prod-pagopa

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
DELETE_OLD_PG_MANAGERS activity implementation
This activity is responsible of finding all the managers of an institution and check on related registry (ADE or INFOCAMERE) if they are still managers. In case they are not managers anymore will be deleted from institution.
local env
> [PNPG-250] feat: DELETE_MANAGERS_BY_IC_AND_ADE activity implementation

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForUsersPg.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
added WorkflowExecutorForUsersPg
This workflow is able to perform the deletion of old pg managers inactive, and create the new manager.
> [PNPG-249] feat: added WorkflowExecutorForUsersPg

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/OnboardingFunctionConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/PagoPaSignatureConfig.java
- apps/onboarding-functions/src/main/resources/application.properties
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/NamiralSignServiceImpl.java
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/client/NamirialHttpClient.java
- modify NAMIRIAL URL from test to container app
- make NAMIRIAL_BASE_URL an environment variable
- set USER and PASSWORD inside onboarding-sdk
It was tested by running onboarding-functions locally and setting NAMIRIAL_BASE_URL to the dev container app url
> [SELC-5798] feat: modify NAMIRIAL URL from test to container app

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/ProductRole.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/service/ProductServiceDefaultTest.java
- test-coverage/pom.xml
Added new attribute productLabel to ProductRoleInfo that indicates a custom description of role product in exceptional case such as prod-pagopa. This label is used on external-api
It is added for this [needed](https://pagopa.atlassian.net/wiki/spaces/SCP/pages/1238892761/RFC+-+Ruolo+di+Prodotto+basato+su+Tipologia+Institution)
> [SELC-5860] feat: add productLabel to ProductRoleInfo on SDK, version 0.3.4

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/OnboardingMapperTest.java
- set  admin aggregate's role to ADMIN_EA when product is PagoPA
The setting of role ADMIN_EA for PagoPA aggregates was needed to manage the actions allowed for pagoPA aggregates.
It was tested by invoking Onboarding Orchestrator locally on a onboarding with aggregates and product prod-pagopa
> [SELC-5786] feat: set admin aggregate's role to ADMIN_EA

- apps/onboarding-functions/src/main/openapi/openapi.json
Hotfix for update openapi as external.v2
> [SELC-5851] Adding acknowledgment to openapi onboarding fn

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingImportContract.java
Removed required field filenamefor import psp
This constraint's deletion is necessary for external-api in order to invoke the psp import api without this parameter (that in this case will be built from product json)
> [SELC-5804] fix: Removed required field filename for import psp

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/PHASE_ADDITION_ALLOWED.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/Product.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/entity/ProductTest.java
- test-coverage/pom.xml
- add userAggregatorContractMappings field in Product
- add "dashboard-aggregator" as PHASE_ADDITION_ALLOWED enum
- upgrade sdk version from 4.0.0 to 4.0.1
> [SELC-5872] feat: add userAggregatorContractMappings field in Product entity in onboarding-sdk

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/Utils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- In the various completion APIs, a file has been added to the request as an input parameter
- the service logic has been revised as these APIs previously exploited a common method which was also used for the onboarding flow from FE
- the method that uses the complete API has been revised as it is useful for the completion logic. Except that unlike the complete, when the compilation is invoked the Token is also created on the DB
This change was necessary because when SM carried out manual onboarding it manually stored the contract on Azure storage. This behavior, in addition to being dangerous and cumbersome, did not even allow the automatic creation of the Token in the collection of the same name on the DB
the API was invoked and it was verified that the Token was created on the DB and …
> [SELC - 6127] feat: updated onboardingCompletion APIs logic to accept file in input

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorConfirmation.java
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
-set status to REQUEST in Onboarding completion APIs
This change is necessary as SM will first have to create an onboarding request and then invoke another API to load the signed agreement and complete the same request. Here the logic has been revised so that in the case of invoking the API the request is put in Request and the Request phase is executed which includes creation of the contract and saving of the Token on the DB also in the workflowType CONFIRMATION
the local ms was started and the api was invoked and onboarding was subsequently completed
> [SELC-6174] feat: rework onboarding completion logic

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerPT.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerSELC.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerSELCTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
added check on workflow type for SELC Manager and default origin and originId
Added a check on the workflow type field to ensure that a SELC onboarding can proceed only in the case of IMPORT or human VALIDATION
local env
> [SELC-6062] feat: added check on workflow type for SELC Manager and default origin and originId

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/BusinessData.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerSELC.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefaultTest.java
- Updated PdfMapper for GPU Data+
- Added placeholders for attachment 'Checklist'
- Fixed method getContract adding condition for token type equals to INSTITUTION
In order to display GPU data into Checklist attachment, new placeholder have been added into PdfMapper
I have deployed the feature branch in DEV and tested the download of the attachment.
> [SELC-6170] feat: Updated PdfMapper for GPU Data

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/DocumentController.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/DocumentControllerTest.java
Added new controller DocumentController
Added new endpoint list-file
this endpoint takes as input the path and returns all the files that are present on the storage from it.
dev - local
> [SELC-6156] Added new DocumentController

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/SapNotificationBuilder.java
SAP now can actually process only ORIGN=[SELC,IPA]. 
When ad institution contains ORIGIN=PDND_INFOCAMERE should be modified into SELC only for SAP notification queue.
> [SELC-6241] SAP: set Origin = SELC if not IPA

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/DocumentController.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/DocumentControllerTest.java
Added decoding for path
Fixed issues due to input path exaping character
> [SELC-6156] feat: Fixed path of endpoint

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- implement aggregates csv creation for SEND by invocking user registry
- align unit tests
> [SELC-6140] feat: manage aggregates csv for SEND

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/OnboardingWorkflowAggregator.java
- change getContractTemplatePath for aggregators with InstitutionAggregatorContractTemplate path value
- change getContractTemplateVersion for aggregators with InstitutionAggregatorContractTemplate version value
This update introduces changes to distinguish aggregator contract templates from standard contract templates. This differentiation ensures proper handling and identification of templates based on their specific use case.
It was tested locally.
> [SELC-6141] feat: change getContract for aggregators

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- mapping placeholders in send aggregates contract
> [SELC-6144] feat: mapping placeholders in send aggregates contract

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Changed response for api check-manager in case of empty onboardings (after filtering them for managerId in input)
The scenario considered as if the legal representative had not changed
I have deployed teh feature branch and tested the specific api check-manager
> [SELC-6245] feat: fixed scenario for check manager in case of empty onboardings

- apps/onboarding-cdc/src/main/openapi/onboarding_functions.json
- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingV2Controller.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/OnboardingResponseV1.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/PartyRoleV1.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/UserOnboardingResponseV1.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/openapi/core.json
- apps/onboarding-ms/src/main/openapi/onboarding_functions.json
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingV2ControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapperTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/AggregatesServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/pom.xml
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/PartyRole.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- test-coverage/pom.xml
- add new enum in PartyRole ADMIN_EA_IO
- upgrade onboarding-sdk to version 0.6.7
- create new versione v2 of the following exposed APIs: 
- POST /v2/onboarding/completion
- GET /v2/onboarding/institutionOnboardings
- POST /v2/onboarding/pa/completion
- POST /v2/onboarding/pg/completion
- POST /v2/onboarding/psp/completion
- mapping v1 response to avoid breaking changes in exposed APIs
- add and modify unit tests
> [SELC-6373] feat: add new PartyRole ADMIN_EA_IO

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/OnboardingMapperTest.java
- set role ADMIN_EA for prod-io during onboarding and when adding a new user
- add unit tests
> [SELC-6374] feat: set role ADMIN_EA for prod-io aggregates

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerSELC.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- set CONTRACT_REGISTRATION workflowType for products with parent
All products that have a parent must follow a CONTRACT_REGISTRATION workflowType, i.e. they do not have to go through the validation of the institution data by the SelfCare admin, this is because the validation has already been performed for the parent product and the data used for joining the child product are similar to those used previously
the MS was started locally and various scenarios were tested to verify that the workflowType was set correctly both for products that have a parent and for those that do not
> [SELC-6435] feat: set CONTRACT_REGISTRATION workflowType for products with parent

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- persist billing to onboarding user request
This small change was necessary because in the onboarding flow of an administrator when the contract is created there is a need to map the VAT number in the contract itself, this is only possible if we persist the Billing data
the MS was started locally and a user onboarding request was executed, verifying that the VAT number was mapped in the contract
> [SELC-6500] feat: persist billing to onboarding user request

- .github/workflows/call_code_review.yml
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/InstitutionController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/GetInstitutionRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/InstitutionService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/InstitutionServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/InstitutionControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/InstitutionServiceDefaultTest.java
- Added api to retrieve institutions given a list of ids
- Added business logic to get data from db and map into a InstitutionResponse object
- Added unit tests for controller and service layers
This api will be invoked from BFF to get the institution type for a set of institutions
I have run the microservice locally and tested the API POST /v1/institutions, checking the response status code and the elements into list
> [SELC-6625] feat: added api to retrieve institutions given a list of ids

- apps/onboarding-cdc/src/main/openapi/onboarding_functions.json
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorConfirmationAggregator.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorContractRegistrationAggregator.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerSELC.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/openapi/onboarding_functions.json
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- added CONFIRMATION_AGGREGATOR WorkflowType
- added new api for SM to complete onboarding aggregator
- added new logic to verify existing onboarding for aggregate
A good part of the logic of the onboarding of aggregator entities has been revised, in particular now when an entity that is present in the list of aggregates was already onboarded on AR, it is not created and provisioned and an onboarding is completed again creating problems for datalake, but simply the delegation is created between the aggregate and the aggregator. In addition, the api for SM has been corrected by adding a new WorkflowType dedicated to adding aggregators/aggregates.
the MS was started locally and the whole process was tested to verify that an entity already present on AR but present as an aggregate was not …
> [SELC-7142] feat: refactor onboarding aggregator/aggregate logic

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/UserMapper.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorContractRegistration.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorContractRegistrationAggregator.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForApprove.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForApproveGpu.java
- apps/onboarding-functions/src/main/openapi/user.json
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- added logic to send mail for user during onboarding request phase
Many times users do not have access to the institution's PEC or do not look at it at all, for this reason to notify the arrival of an onboarding request you want to send a notification to the user's email.
a request to join was sent and it was verified that the email was sent to the user
> [SELC-6979] feat: added logic to send mail for user during onboarding request phase

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- added logic to retrieve taxCode for PRV_PF
- removed soleTrader boolean 
Due to the new "Appliance Bonus Initiative," sole trader (PRV_PF) can now participate. In these cases, the institution's fiscal code is the same as the individual's personal fiscal code. To comply with corporate GDPR policies, this data must be tokenized using the PDV system. For this reason, all of these related processes have been adapted.
All the APIs involved in the changes were called to verify the correct  detokenization of the data, ensuring the pre-existing logic was not impacted.
> [SELC-7710] feat: added logic to retrieve taxCode for PRV_PF
