- .github/workflows/deploy.yml
Create workflow gtihub action for deploy when pr is closed on develop
> Deploy pipeline

- .github/workflows/code_review_onboarding_ms.yml
- .github/workflows/deploy_onboarding_ms.yml
Added code review onbarding ms
Added deploy onbarding ms
> Added code review and deploy ms

- .github/workflows/deploy_onboarding_ms.yml
- .identity/00_data.tf
- .identity/03_github_environment.tf
- .identity/99_variables.tf
- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
- onboarding-ms/deploy-image-container-app.yaml
- onboarding-ms/src/main/resources/application.properties
* Added checkout to steps deploy
* Fix if environment workflow
* Added USER_REGISTRY_URL and USER_REGISTRY_API_KEY
Deploy to.container apps does not working
> Fix workflow deploy onboarding ms

- .github/workflows/deploy_onboarding_ms.yml
- onboarding-ms/src/main/java/it/pagopa/selfcare/controller/OnboardingController.java
- onboarding-ms/src/main/java/it/pagopa/selfcare/controller/request/BillingSaRequest.java
- onboarding-ms/src/main/java/it/pagopa/selfcare/controller/request/OnboardingSaRequest.java
- onboarding-ms/src/main/java/it/pagopa/selfcare/mapper/OnboardingMapper.java
- onboarding-ms/src/main/java/it/pagopa/selfcare/service/OnboardingService.java
- onboarding-ms/src/main/java/it/pagopa/selfcare/service/OnboardingServiceDefault.java
- onboarding-ms/src/main/java/it/pagopa/selfcare/service/strategy/ConfigMapAllowedListOnboardingValidationStrategy.java
- onboarding-ms/src/main/openapi/core.json
- onboarding-ms/src/main/resources/application.properties
- onboarding-ms/src/test/java/it/pagopa/selfcare/controller/OnboardingControllerTest.java
- onboarding-ms/src/test/java/it/pagopa/selfcare/service/OnboardingServiceDefaultTest.java
- onboarding-ms/src/test/java/it/pagopa/selfcare/service/strategy/ConfigMapAllowedListOnboardingValidationStrategyTest.java
- onboarding-ms/src/test/resources/application.properties
* Added onboarding for institutionType SA
* Added check if institution has already anonboarding
We need to onboard also institutionType SA that has different required fields. 
Try to call POST /onboarding/sa
> SELC-2983 - onboarding institutionType SA

- onboarding-functions/src/main/java/it/pagopa/selfcare/service/ContractService.java
- onboarding-functions/src/main/java/it/pagopa/selfcare/service/ContractServiceDefault.java
- onboarding-functions/src/main/java/it/pagopa/selfcare/service/OnboardingService.java
- onboarding-functions/src/test/java/it/pagopa/selfcare/service/ContractServiceDefaultTest.java
- onboarding-functions/src/test/java/it/pagopa/selfcare/service/OnboardingServiceTest.java
Added method for load contract from azure storage 
Some contract have already exists, we don't build using a template. We only load and save on storage.
> load contract from azure storage

- .identity/99_variables.tf
Rename container app environment
> rename container app env

- .github/workflows/code_review.yml
- .github/workflows/code_review_functions.yml
- .github/workflows/code_review_ms.yml
- onboarding-ms/deploy-image-container-app.yaml
* Added core_review workflow as template
* Added core_review_ms for code review of onboarding-ms
* Added core_review_functions for code review of onboarding-functions
We want different code reviews for each submodule (onboarding-ms, onboarding-functions ecc..), workflow is the same but change only the path retrieve pom.xml. We create a template action that will be used by ms and functions code reviews
> ops: code reviews as template

- .github/workflows/release_onboarding_sdk.yml
Added permissions packages write
Previous PR has removed permission wrongly
> fix: release sdk cd

- .container_apps/onboarding-ms/container_app.tf
- .container_apps/onboarding-ms/locals.tf
- .container_apps/onboarding-ms/outputs.tf
Add an record to the azurecontainerapps.io private DNS zone to resolve requests to the container app onboarding-ms
The need to resolve domain into the container app environment static IP forces us to set an A DNS record in the private DNS zone
> add dns private for ca onboarding ms

- .github/labeler.yml
- .github/workflows/release_onboarding_sdk.yml
- libs/onboarding-sdk-pom/pom.xml
- libs/pom.xml
* Updated GitHub Actions workflow:
* Changed the parent artifact ID to onboarding-libs.
These changes are required to address an issue encountered with the SonarQube Maven plugin, specifically the "Unable to determine structure of project orphan" problem. The plugin was failing to recognize some structures of Maven modules. By reorganizing the project hierarchy in onboarding-libs and adjusting Maven configurations, these changes aim to resolve this issue and improve the overall build and analysis process.
> fix: maven configuration for SonarQube compatibility

- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
* Upgrade last version of Quarkus 3.5.2
* Upgrade quarkus-openapi-generator 2.2.13
* fix if statement on workflow deploy ms
> upgrade quarkus 3.5.2

- .dockerignore
- apps/onboarding-ms/Dockerfile
Modified the Dockerfile of the OnboardingMS image to include a copy of the pom.xml file from the test-coverage module. This change ensures that the test-coverage module is properly incorporated into the Docker image, addressing the issue where the refactor for enabling test coverage on SonarQube broke the Docker image creation.
This is the temporary solution, it will be modified removing incorporate all sub-modules.
This change was necessary because the recent refactor aimed at enabling test coverage on SonarQube inadvertently caused a problem in the Docker image creation process for OnboardingMS. Specifically, the root pom.xml, which now includes the test-coverage module, was not being fully represented in the Docker image. By adding the copy directive for the test-coverage module's …
> add test-coverage pom to dockerfile

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Token.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/repository/TokenRepositoryTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
* Implemented CONTRACT_FILENAME_FUNC which is responsible for generating the contract file name by incorporating the product name.
* Incorporated the use of CONTRACT_FILENAME_FUNC in the contract saving and retrieval flows to ensure that the contract file names are more descriptive and include the product title reference.
This change was necessary to enhance the clarity and descriptiveness of contract file names in the asynchronous onboarding flow. Previously, the file names were only identified by the onboarding ID, which was less informative. By including the product title in the file name, it becomes more immediately clear which contract is associated with which product, thereby improving file management and ease of identification in the Azure storage system.
> [SELC-2862] fix: contract filename as legacy ms-core

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/BillingRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/InstitutionBaseRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingPaRequest.java
- apps/onboarding-ms/src/main/resources/application.properties
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
1. **Removal of the /onboarding/sa endpoint**: This change aligns the onboarding process for institution type SA with the standard onboarding process implemented via the /onboarding endpoint. The dedicated endpoint for type SA has been removed as it is no longer necessary.
2. **Addition of digitalAddress as a Required Attribute**: The attribute 'digitalAddress' has been added as a required field to ensure completeness and accuracy in the onboarding information.
3. **Addition of OpenAPI Documentation**: Updated the OpenAPI documentation to reflect the changes in the onboarding process and the new requirement of the 'digitalAddress' attribute.
The removal of the /onboarding/sa endpoint simplifies the onboarding process by following a uniform approach for all institution types, enhancing the …
> [SELC-2862] fix: remove SA onboarding

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/OnboardingCompletionFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/client/auth/AuthenticationPropagationHeadersFactory.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/InstitutionMapper.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/OnboardingCompletionFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
1. **Addition of MS-Core REST Client**: A new REST client for ms-core has been integrated to facilitate communication with ms-core services.
2. **Integration of CompletionService**: Added CompletionService, crucial for implementing the business logic required to complete an onboarding process.
3. **Implementation of Institution Creation Method**: Developed a new method to handle the creation of an institution, ensuring its presence post-onboarding process.
4. **Inclusion of MapStruct Library**: Integrated the MapStruct library to aid in the creation of mappers, enhancing data transformation and mapping capabilities.
This change is required to enhance the onboarding process. At the end of the onboarding completion, it's essential to verify the presence of an institution and create it if …
> [SELC-3452] feat: create institution on completion of onboarding process

- libs/onboarding-sdk-azure-storage/src/main/java/it/pagopa/selfcare/azurestorage/AzureBlobClient.java
- libs/onboarding-sdk-azure-storage/src/main/java/it/pagopa/selfcare/azurestorage/AzureBlobClientDefault.java
- libs/onboarding-sdk-product/README.md
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceCacheable.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/service/ProductServiceCacheableTest.java
- libs/onboarding-sdk-product/src/test/resources/mockito-extensions.properties
Introduced a new Cacheable product that can update itself if the storage get's updated
The previous implementation doesn't automatically account for product's modification in the storage, it would send the updated object only if the microservice gets restarted. With the new cacheable Product every time a method of the Productservice gets called a refresh method checks and ensures that the retrieved product is up to date
> [SELC-3438] feat: introduce Cache Product Service

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/OnboardingCompletionFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/OnboardingCompletionFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
1. **Azure Function for Onboarding Completion Email:** Implemented an Azure function to send an email notification upon the completion of an onboarding process.
2. **Email Address Retrieval from Work Contracts**: Enhanced the system to fetch the email address of the 'MANAGER' role from the work contracts associated with the institution that has completed the onboarding.
One step of completion of an onboarding process consist on notifying the 'MANAGER' role of the institution about onboarding success. Implementing an Azure function for email notification ensures an automated, reliable, and timely update to the relevant stakeholders. Additionally, retrieving the manager's email address from work contracts streamlines the process, ensuring that the notification is sent to the correct …
> [SELC-3452] feat: send mail of completion onboarding process

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/OnboardingCompletionFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/UserMapper.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/OnboardingCompletionFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
* Add ms-core rest client
* Azure function for persist onboarding
* Service method for create request and call ms-core
Added new step to complete the onboarding workflow. This function call ms-core to create the association of the institution and users with a product in an ACTIVE state
> [SELC-3504] feat: persist onboarding on completion process

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/OnboardingStatus.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- test-coverage/pom.xml
1. Refactored the possible states that an onboarding request can have.
2. Upgraded the version to 0.1.3. 
The onboarding process involves several steps before concluding with the creation of an institution and its association with the product. Look at https://pagopa.atlassian.net/wiki/spaces/SCP/pages/776339638/DR+-+Domain+Onboarding for more information about states.
> [SELC-3504] feat: added onboarding status

- .functions/onboarding-functions/env/dev/terraform.tfvars
- .functions/onboarding-functions/env/uat/terraform.tfvars
Added MS_CORE_URL env to functions infrastructure
Missing MS_CORE_URL env when onboarding completion process is triggered causing 404 exception.
> fix: add MS_CORE_URL env to functions

- .container_apps/onboarding-ms/env/dev/terraform.tfvars
- .container_apps/onboarding-ms/env/uat/terraform.tfvars
* Increase replica to 1
* Added SIGNATURE_VALIDATION_ENABLED env
* Added secret for azure storage
Onboarding-ms should be always live because its startup time takes about 1 minute. It uses [DSS Digital Signature Service](https://github.com/esig/dss) for signature validation and it loads some certification during startup time.
> ops: increase replica and disabled signature

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
* Fix set institutionName on create contract during onboarding process
* Added parameter name to contract file on onboarding complete
> [SELC-3452] fix: institutionName mapper on create contract

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/RetryPolicyConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingCompletionFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/resources/application.properties
Added retry policy as config in terms of:
* maxAttempts
* firstRetryInterval
* backoffCoefficient
Look at for more information https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-error-handling?tabs=csharp-inproc
> ops: retry policy as config

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
Fix accents on contract file name when creating
Accents cause errors when saving contract
> fix: contract file name with accents

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/OnboardingGet.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/exception/handler/ExceptionHandler.java
* Added handler to 404 for resource not found
* Remove unused output datetime attribute
We want to return 404 when service throws resource not found
> [SELC-3509] fix: handler for resource not found

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/GeographicTaxonomy.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/InstitutionMapper.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/GeographicTaxonomyDto.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/InstitutionBaseRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/InstitutionResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/GeographicTaxonomy.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
* **Added geotaxonomy in the request when onboarding institution**. This enhancement allows the association of geotaxonomy during the creation of an institution. 
* Fix mapping data when create pdf contract
This change addresses the lack of geotaxonomy integration in the process of creating an institution. By incorporating geotaxonomy in the request, the system now aligns better with the onboarding phase requirements and ensures a more comprehensive creation of institutional data.
> [SELC-3503] fix: enhance onboarding with geotaxonomy integration

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
Fix mapper user mail when create pdf contract
> fix: mapper mail when create contract

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/UserMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
New GET Endpoint for Onboarding by ID with User information: Implemented a new endpoint to retrieve an onboarding record given its ID that added user information such as fiscal code, name and surname. This enhancement allows the front-end to provide onboarding data for administration approving.
The addition of this endpoint is driven by the need for the front-end to effectively verify the data of an onboarding process when an admin must be approve the onboarding. The 'GET onboarding by id' endpoint facilitates access to onboarding records with user information.
> [SELC-3493] feat: add new endpoint for onboarding process verification by admin

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
Fix mapper delegate's mail when create pdf contract
> fix: mapper delegate's mail when create contract

- infra/mongo/.terraform.lock.hcl
- infra/mongo/env/dev/backend.ini
- infra/mongo/env/dev/backend.tfvars
- infra/mongo/env/dev/terraform.tfvars
- infra/mongo/env/uat/backend.ini
- infra/mongo/env/uat/backend.tfvars
- infra/mongo/env/uat/terraform.tfvars
- infra/mongo/locals.tf
- infra/mongo/main.tf
- infra/mongo/mongo_db.tf
- infra/mongo/outputs.tf
- infra/mongo/terraform.sh
- infra/mongo/variables.tf
Import to main branch the TF mongodb configuration
Config was stored under `.identity` and in `develop` branch only. Not correct
> [EC-77] Import MongoDb TF configuration

- infra/mongo/.terraform.lock.hcl
- infra/mongo/env/dev/backend.ini
- infra/mongo/env/dev/backend.tfvars
- infra/mongo/env/dev/terraform.tfvars
- infra/mongo/env/uat/backend.ini
- infra/mongo/env/uat/backend.tfvars
- infra/mongo/env/uat/terraform.tfvars
- infra/mongo/locals.tf
- infra/mongo/main.tf
- infra/mongo/mongo_db.tf
- infra/mongo/outputs.tf
- infra/mongo/terraform.sh
- infra/mongo/variables.tf
Import to develop branch the new cosmos config
Branch alignment
> [EC-77] Import MongoDb TF configuration (#87)

- apps/onboarding-functions/host.json
limit ExtensionBundle to 4.8.1 version
Avoid to upgrade Grpc.Core on Mac M1 when azure core tools upgrade
> ops: limit ExtensionBundle to 4.8.1 version

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/MailTemplatePathConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/SaveOnboardingStatusInput.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/OnboardingStatus.java
* Updated the workflow FOR_APPROVE so that the subsequent state to REQUEST is now TO_BE_VALIDATED.
* For the FOR_APPROVE workflow, transitioning from TO_BE_VALIDATED to PENDING now triggers the sending of an email to the institution with the contract for signing.
* For the FOR_APPROVE_PT workflow, completing an onboarding now sends a dedicated email specific to the PT type.
This change is required to enhance the onboarding request flow for certain types that necessitate approval by a selfcare admin. Initially, the request enters a TO_BE_VALIDATED state and upon approval, it transitions to PENDING. This process also includes the crucial step of sending the contract to the entity for signing. Additionally, the introduction of a specialized email for the FOR_APPROVE_PT workflow caters to the …
> [SELC-349] Enhanced onboarding flow with admin approval in FOR_APPROVE workflows

- .github/auto_assign.yml
- .github/workflows/check_pr.yml
- .github/workflows/code_review_functions.yml
- .github/workflows/code_review_libs.yml
- .github/workflows/code_review_ms.yml
- .github/workflows/deploy_onboarding_functions.yml
- .github/workflows/deploy_onboarding_ms.yml
Added deploy ms and function when a new branch 'release' has been created.
Implementation of git strategy described here https://pagopa.atlassian.net/wiki/spaces/SCP/pages/765952327/RFC+-+Semplificare+processo+di+deploy
> ops: workflow for trunk-based strategy

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Replace call to endpoint orchestrator complete with start orchestrator onboarding.
Refactor of onboarding-ms about this [PR](https://github.com/pagopa/selfcare-onboarding/pull/99)
> [SELC-3883] refactor: replace start orchestrator complete when approve or complete onboarding

- .identity/env/dev/terraform.tfvars
Remove reviewers to confirm deployment in dev-cd
dev-cd releases in dev env. We don't need to validate this easy deployment
> Remove reviewers for dev-cd environment

- .github/workflows/pr_functions.yml
- .github/workflows/pr_libs.yml
- .github/workflows/pr_ms.yml
Fix workflows file names
Files were renamed, triggers not
> Fix trigger paths for PR pipelines

- .github/workflows/pr_functions.yml
- .github/workflows/pr_libs.yml
- .github/workflows/pr_ms.yml
Add permission to read packages
Code review need to read github packages
> ops: add permission read github packages

- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
replace TO_BE_VALIDATED to TOBEVALIDATED with different version
The right onboarding status is TOBEVALIDATED
> fix: TOBEVALIDATED onboarding ms

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
Save workflow instanceId and status FAILED if workflow fails
Useful information for troubleshooting when an onboarding request has been not completed
> [SELC-3580] feat: handling FAILED workflow

- .github/workflows/call_code_review_infra.yml
- .github/workflows/call_release_infra.yml
- .github/workflows/pr_container_apps_infra.yml
- .github/workflows/pr_functions_infra.yml
- .github/workflows/pr_mongo_infra.yml
- .github/workflows/release_container_apps_infra.yml
- .github/workflows/release_functions_infra.yml
- .github/workflows/release_mongo_infra.yml
- .github/workflows/release_ms.yml
- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
- infra/functions/onboarding-functions/.terraform.lock.hcl
- infra/functions/onboarding-functions/functions.tf
Add pipelines to apply TF configurations
Update identities roles to make pipelines work
I like automation
> [EC-101] PR and Release pipelines for TF configurations

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
* Added workflow step for REJECTED status
* MS will trigger orchestration when rejection is called
Rejection must be notified to user
> [SELC-2865] feat: send mail when onboarding is REJECTED

- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
Onboarding ms container app min replicas to 1 for dev and prod
Onboarding ms take long time to startup because load some certificates from external resources. Its instance should be always live.
> ops: onboarding ms min replicas to 1

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForApprovePt.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
Fix call default method when execute TOBEVALIDATED step.
Workflow APPROVE_PT do nothing when execute TOBEVALIDATED step.
> [SELC-3882] fix: TOBEVALIDATED step when APPROVE_PT

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/OnboardingFunctionConfig.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/conf/OnboardingMsConfig.java
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceDefault.java
- test-coverage/pom.xml
* Fix product sdk
* Config ProductServiceCacheable as productService 
ProductServiceCacheable is used for obtain product configuration real-time updated.
> [SELC-3198] feat: using ProductServiceCacheable

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
Fixed logic on checkOnboarding for product and productParent
The onboarding for prod-io-premium was failing due to incorrect validation of its parent onboarding check, the error correctly thrown wasn't catched and processed
> Fixed check for children product's onboarding

- .github/workflows/create_release_branch.yml
- .identity/.terraform.lock.hcl
- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
- .identity/github_branch_rules.tf
- .identity/github_environment_cd.tf
- .identity/github_environment_ci.tf
- .identity/github_managed_identity_cd.tf
- .identity/github_managed_identity_ci.tf
- .identity/locals.tf
- .identity/main.tf
- .identity/variables.tf
Trigger other pipelines when a new release branch is created
Set branch rules to avoid any mistake with automation
A bit of automation
> [EC-106] Trigger pipelines when a new release branch is created

- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
- add "prod-sendino" in ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS in terraform.tfvars in dev and uat environment
This change allows to complete onboarding for sendino product in dev and uat environment through new onboarding microservice.
> feat: add prod-sendino in ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingPgRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
PG institution type as default when onboarding/company
onboarding/company is used only on PNPG use case where institution type is PG
> [SELC-3996] fix: PG as default when onboarding/company

- apps/onboarding-functions/src/main/resources/application.properties
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
Added mail template pt complete values
mail-template-pt-complete references are about mail that is send when an institution pt is onboarded
> ops: mail template pt complete values

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/TokenController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/TokenResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/TokenMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/TokenControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefaultTest.java
Added GET tokens using an onboardingId
List of token is used by BFF external-api backend to expose file contract
> [SELC-4009] feat: get token by onboardingId

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
When create pdf contract, if template path is pdf the function get file without parsing onboarding values
Some use case, for ex. Fideiussioni, we have already the contract without needed to add onboarding data
> [SELC-3578] feat: get file contract if template path is pdf

- infra/container_apps/onboarding-ms/terraform.sh
- infra/functions/onboarding-functions/terraform.sh
- infra/mongo/terraform.sh
Update all terraform.sh files
Manual init to reconfigure backend was required. Updating the terraform.sh is easier than changing pipelines accordly
> [EC-114] Update terraform.sh to execute init before any other command

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingBaseRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingPgRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Product.java
Remove userid from onboarding request
It is not needed for onboarding request
> refactor: remove userid from onboarding request

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/InstitutionType.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- test-coverage/pom.xml
Added new InstitutionType REC CON
REC is for Recapitisti
CON is for Consolidatori
> [SELC-3832] feat: add new InstitutionType REC CON

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/openapi/core.json
* Using upgrade onboarding sdk version 
* Update core openapi for using REC and CON
> [SELC-3832] feat: update openapi and using upgrade sdk version

- apps/onboarding-functions/src/main/resources/application.properties
Increase core rest client timeout to 60000ms
Persist onboarding could take a long time
> ops: increase core client timeout

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
Added consume endpoint for complete onboarding without signature verification of the contract
It is used for operations when digest errors happen
> [SELC-4016] feat: consume onboarding endpoint

- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- add "prod-sendino" in  ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS in prod environment
This change allows to complete onboarding for sendino product in prod environment.
> [SELC-3991] feat: add prod-sendino in ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS in prod

- .identity/data.tf
- .identity/github_branch_rules.tf
- .identity/github_managed_identity_ci.tf
Add permissions on pnpg keyvault to github managed identity
Pipelines need to read data from pnpg keyvault
> [EC-116] Add permission on pnpg keyvault to managed identity

- .github/workflows/pr_libs.yml
- .github/workflows/release_onboarding_sdk.yml
Add path to filter triggers
Release a new sdk version only when code is changed
> [EC-161] Fix onboarding release trigger

- .github/workflows/release_pnpg_functions.yml
- .github/workflows/release_pnpg_ms.yml
Added workflow for release ms on PNPG
Added workflow for release functions on PNPG
> [EC-116] ops: release PNPG ms and functions

- infra/mongo/mongo_db.tf
> ops: remove mongo lock onboardings

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingPgRequest.java
Remove mail vvalidation on OnboardingPg request
It cause some issues on openapi pattern
> fix: remove mail validation on PG request

- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
set USER_REGISTRY_URL dev value to api.uat
> fix: USER_REGISTRY_URL dev value

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/InstitutionResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/OnboardingGet.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
Added properties into OnboardingGet object
This change is linked to new API added into external-ms that retrieves tokens from new onboarding backend. 
I have run the microservice locally and tested the **API GET /onboardings** verifying the values in response.
> [SELC-4086] feat: Added properties into OnboardingGet object

- .github/workflows/call_code_review_infra.yml
- .github/workflows/call_release_function.yml
- .github/workflows/call_release_infra.yml
- .github/workflows/call_release_ms.yml
- .identity/locals.tf
Rename az env vars
Consistent naming, already applied in main
> [CP] Rename GitHub secrets and variables

- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
- infra/mongo/mongo_db.tf
* Added indexes for createdAt on tokens and onboardings
* set STORAGE_CONTAINER_CONTRACT for uat and prod
GET endpoints return records ordered by createdAt
> [SELC-3555] ops: added indexes createdAt

- infra/container_apps/onboarding-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat-pnpg/terraform.tfvars
> fix: aks url uat and prod

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/exception/ResourceConflictException.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/exception/handler/ExceptionHandler.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/GenericError.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Added ResourceConflictException which is throwed when an onboarding is founded during onboarding request process
Selfcare handles this http code showing an custom error page
> fix: return http code 409 when already onboarded

- .github/workflows/create_release_branch.yml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat-pnpg/terraform.tfvars
* Update date of updateAt when worflow is executed
* Enable trigger of release PNPG functions
* Some env values for PNPG uat and prod
UpdateAt show us when record has been updated last time
> fix: save updateAt when workflow executed

- .github/workflows/pr_functions.yml
- .github/workflows/pr_ms.yml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/conf/OnboardingMsConfig.java
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
* mongodb client is created at startup app
* enable pipeline pr also for release branch
* disable signature verification on uat env
> fix: mongodb client at startup

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Fix recover failure if parent has an onboarding 
It causes error in onboarding on prod-io-premium
> fix: return conflict if parent has an onboarding

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
Added BsonProperty to institution model
Institution id was not mapped when queries retrieve onboarding data
> fix: mapping using BsonProperty for institutionId

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/exception/handler/ExceptionHandler.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/exception/model/Problem.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/exception/model/ProblemError.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/exception/handler/ExceptionHandlerTest.java
* Signature failure must return an http error with a Problem entity as body
* Run signature method on DefaultWorkerPool to avoid blocking call
Selfcare frontend receive an Problem body when signature fails and it shows appropriate error message based on error code present inside Problem entity.
> fix: return Problem entity as body on Signature failure

- .github/workflows/release_container_apps_infra.yml
- .github/workflows/release_container_apps_pnpg_infra.yml
- .github/workflows/release_functions_infra.yml
- .github/workflows/release_functions_pnpg_infra.yml
- .github/workflows/release_mongo_infra.yml
- .github/workflows/release_mongo_pnpg_infra.yml
- apps/onboarding-ms/src/main/resources/application.properties
Permit release feat branch on uat environment
> ops: enable release feat branch on uat

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/filter/CustomClientLoggingFilter.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/filter/CustomClientRequestLoggingFilter.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/filter/CustomClientResponseLoggingFilter.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/filter/CustomLoggingFilter.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/resources/application.properties
- test-coverage/pom.xml
* Added http request filter at ingress/outboudn for customize logging
* Fix verify not null contract at complete endpoint
Logging can be useful for troubleshooting when errors happen
> [SELC-4158] feat: adding logging customizing http request-response

- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
MAIL_DESTINATION_TEST sending mail to MAIL_DESTINATION_TEST_ADDRESS if is true
> ops: enable send real mail

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/OnboardingFunctionConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/PagoPaSignatureConfig.java
- apps/onboarding-functions/src/main/resources/application.properties
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
Refactor creating PadesSignService
Azure function cause some problem with Quarkus option IfBuildProperty.
> fix: set sign service based on pagopa source resource

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/resources/application.properties
Added quarkus.smallrye-openapi.store-schema-directory to indicare where saving openapi
> [SELC-4938] feat: save openapi under docs folder

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
Replace updateAt with updatedAt
updatedAt is the right name for attribute that indicate when a record has been updated
> fix: replace updateAt with updatedAt

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
Remove request to pdv for retrieving user details when sending mail approve with contract
Use details is not used when sending mail approve with contract.
> fix: avoid to find unused user request

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/filter/CustomClientRequestLoggingFilter.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/filter/CustomClientResponseLoggingFilter.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
Added setting UID as id when onboarding using import pa
> hotfix: mapping onboarding ID for import workflow

- infra/functions/onboarding-functions/functions.tf
Migrating nat and public ip to selfcare-infra as unique ip for all selfcare service
> [SELC-4448] fix: Migrating nat to selfcare-infra

- infra/container_apps/onboarding-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
Set MS_CORE_URL and PROXY_URL endpoint for container app dev env
Migrate to Container Apps environment
> [SELC-4411] chore: set core and party ca url dev

- infra/container_apps/onboarding-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/.terraform.lock.hcl
- infra/functions/onboarding-functions/env/dev-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
Set MS_CORE_URL and PROXY_URL endpoint for container app dev env PNPG
Migrate to Container Apps environment
> [SELC-4411] chore: set core and party ca url dev pnpg

- infra/functions/onboarding-functions/functions.tf
- infra/functions/onboarding-functions/locals.tf
Updating infra for migrate pip to selfcare-infra as unique outbound IP
> [SELC-4448] Feature/selc 4448

- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
Enabling prod-interop-coll to be onboarded
> Adding prod-interop-coll to ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS

- infra/container_apps/onboarding-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
Change core and proxy url to switch to container app in uat and prod environment
Migration to container apps
> chore: [SELC-4411] switch url container app uat and prod

- infra/container_apps/onboarding-ms/container_app.tf
- infra/container_apps/onboarding-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/variables.tf
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
Migration to Container App DEV supporting a workload profile
> chore: Workload profiles migration DEV

- infra/container_apps/onboarding-ms/container_app.tf
- infra/container_apps/onboarding-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
- infra/container_apps/onboarding-ms/variables.tf
- infra/functions/onboarding-functions/env/dev-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
Remove workload_profile_name variables because is default on terraform module
Change PNPG dns suffix url
Migration to new Container Apps environment with Workload profile
> chore: Workload profiles migration PNPG

- .github/workflows/call_release_ms.yml
- .github/workflows/release_hub_spid.yml
- infra/container_apps/hub_spid_login/.terraform.lock.hcl
- infra/container_apps/hub_spid_login/container_app.tf
- infra/container_apps/hub_spid_login/env/dev-pnpg/backend.ini
- infra/container_apps/hub_spid_login/env/dev-pnpg/backend.tfvars
- infra/container_apps/hub_spid_login/env/dev-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/env/dev/backend.ini
- infra/container_apps/hub_spid_login/env/dev/backend.tfvars
- infra/container_apps/hub_spid_login/env/dev/terraform.tfvars
- infra/container_apps/hub_spid_login/env/prod-pnpg/backend.ini
- infra/container_apps/hub_spid_login/env/prod-pnpg/backend.tfvars
- infra/container_apps/hub_spid_login/env/prod-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/env/prod/backend.ini
- infra/container_apps/hub_spid_login/env/prod/backend.tfvars
- infra/container_apps/hub_spid_login/env/prod/terraform.tfvars
- infra/container_apps/hub_spid_login/env/uat-pnpg/backend.ini
- infra/container_apps/hub_spid_login/env/uat-pnpg/backend.tfvars
- infra/container_apps/hub_spid_login/env/uat-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/env/uat/backend.ini
- infra/container_apps/hub_spid_login/env/uat/backend.tfvars
- infra/container_apps/hub_spid_login/env/uat/terraform.tfvars
- infra/container_apps/hub_spid_login/main.tf
- infra/container_apps/hub_spid_login/terraform.sh
- infra/container_apps/hub_spid_login/variables.tf
- infra/functions/onboarding-functions/functions.tf
* Added Release pipeline
* Added Infra folder for Container App
> [SELC-4523] feat: Hub-Spid-Login migration to Container App Env

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
Added prefix for email uuid into pdv model
During onboarding phase, users are created into PDV with a new model. In particular, the workContacts field will be a map with key equals to an identifier of email built in this way: ID_MAIL# + random uuid
> [SELC-4691] feat: added prefix for email uuid into pdv model

- infra/container_apps/hub_spid_login/container_app.tf
- infra/container_apps/hub_spid_login/env/prod-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/env/prod/terraform.tfvars
- infra/container_apps/hub_spid_login/env/uat-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/env/uat/terraform.tfvars
- infra/container_apps/hub_spid_login/locals.tf
- infra/container_apps/hub_spid_login/variables.tf
- infra/container_apps/onboarding-ms/container_app.tf
- infra/container_apps/onboarding-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
- infra/container_apps/onboarding-ms/locals.tf
- infra/container_apps/onboarding-ms/variables.tf
- infra/functions/onboarding-functions/env/dev-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
* Container App env name must be specified
* workload_profile null for dev and prod
Container App env could have a different configuration among dev or uat or prod.
> chore: Migration to Container App module with name and workload_profile empty

- infra/container_apps/hub_spid_login/container_app.tf
- infra/container_apps/hub_spid_login/env/uat-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/env/uat/terraform.tfvars
- infra/container_apps/hub_spid_login/locals.tf
- infra/container_apps/hub_spid_login/variables.tf
- infra/container_apps/onboarding-ms/container_app.tf
- infra/container_apps/onboarding-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
- infra/container_apps/onboarding-ms/locals.tf
- infra/container_apps/onboarding-ms/variables.tf
- infra/functions/onboarding-functions/env/uat-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
Using terraform ca module with suffix
Change cae url uat
Migration uat env with -001 suffix
> chore: Migration uat using terraform ca module with suffix

- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
> fix: added prod-io-sign in ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS

- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
> fix: added prod-io-sign in ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS UAT

- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
* Fix user-ms uat url
* Container App prod url
> hotfix: USER_MS uat and prod url

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/InstitutionBaseRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
Added field originId in DTO and Entity
The field originId is useful in case taxCode is not provided (foreign country institution) to create institution based on origin and originId
local env
> [SELC-4709] feat: added originId in DTO and Entity

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
Updated openapi
Updated openapi
> [SELC-4709] fix: updated openapi

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingDefaultRequest.java
removed NotNull from billing in OnboardingDefaultRequest
To allow onboarding for foreign institutions without billing data
> SELC-4474 feat: removed NotNull from billing object in OnboardingDefaultRequest and updated openapi

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/openapi/core.json
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
modified verifyOnboarding invocation calling new API which adds to the previous accepted parameters, the fields: origin, originId, externalId
Is required to check the onboarding when the institution taxCode is not provided
> [SELC-4686] feat: modified verifyOnboarding invocation calling new API

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
Update field extCountry for italian institution
> [SELC-4472] fix: Update field extCountry for italian institution

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
Add try-catch on userApi.usersUserIdPost
CreateUsers sometimes fails for Connection reset.
> hotfix: add try-catch when CreateUsers

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/BillingPaRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingPaRequest.java
- removed @NotEmpty annotation to billingPaRequest.vatNumber
This change was necessary to allow onboarding to all those institutions that do not have a VAT number
> [SELC - 4576] fix: removed @NotEmpty annotation to billingPaRequest.vatNumber

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- infra/container_apps/hub_spid_login/container_app.tf
- infra/container_apps/onboarding-ms/container_app.tf
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
* Enable prod USER_MS_ACTIVE
* Added initialDelaySeconds to probes
> chore: USER_MS_ACTIVE prod to true

- infra/container_apps/onboarding-ms/container_app.tf
- infra/container_apps/onboarding-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
* set Container app env prod url for core and proxy
* USER_MS_ACTIVE true on prod
> hotfix: set Container app env prod url for core and proxy

- infra/container_apps/onboarding-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
> hotfix: set Container app env prod url for core and proxy (#250)

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/Product.java
- libs/onboarding-sdk-product/src/main/schema/Product_v1.avsc
- added "invoiceable" field in Product entity
- changed version for pom
> feat: add invoiceable field in Product entity and increase sdk version

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
increased onboarding-sdk-common version in onboarding-functions and onboarding-ms
> feat: increased onboarding-sdk-common version in onboarding-functions and onboarding-ms

- infra/container_apps/hub_spid_login/env/prod-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/env/prod/terraform.tfvars
> chore: set hub-spid-login environment var for prod

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/InstitutionBaseRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/InstitutionResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- added taxCodeSfe field in Institution Object functions
- added taxCodeSfe field in Institution Object MS
- added taxCodeSfe field in InstitutionBaseRequest Object MS
The addition of this new field is necessary as some AOO/UO have a taxCode different from that of the central body, which they use for invoicing, called SFE taxCode.
The microservice has been started locally and it has been verified that it is present in the Request
> [SELC - 4786] feat: added taxCodeSfe field in Institution Object

- apps/onboarding-functions/src/main/resources/application.properties
Email template for confirmation onboarding reject should not include motivation text due to legal requirements. 
Rollback to previews version fix this issue.
> [SELC-4828] Downgrade email template version

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest2.java
- infra/functions/onboarding-functions/env/dev-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
added flag that forces the creation of the institution on every onboarding
Solve's bug raised from the implementation done to onboard pnpg institutions
> [SELC-4738] feat: add flag to force institution creation on every onboarding

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/BillingPaRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/InstitutionBaseRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Billing.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Institution.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtilsTest.java
Added custom validation for UO with taxCodeInvoicing. In particular:
1. new check has been addded to verify if parent tax code has been changed during onboarding request
2. new check has been added to verifiy if tax code invoicing has been changed during onboarding request
I have run the onboarding ms locally and tested the API **POST /onboarding**
> [SELC-4918] feat: added custom validation for UO with taxCodeInvoicing

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
Set taxCodeInvoicing into blling node to persist onboardings attribute into Institution object
> [SELC-4931] fix: Set taxCodeInvoicing for persist onboardings function

- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
Removing fd product from onboarding configuration
This configuration is a temporary solution until the FD product is launched.
> Remove prod-fd from onboarding list

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/Product.java
Added consumers field in product object
By inserting the new field we have centralized the mapping between product and consumer names
> [SELC-4980] feat: added consumers field in Product object, and updated pom

- apps/onboarding-cdc/Dockerfile
- apps/onboarding-cdc/pom.xml
- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/OnboardingCdcService.java
- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/entity/Onboarding.java
> [SELC - 4960] feat: added insert as operationType

- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/OnboardingCdcService.java
- apps/onboarding-cdc/src/main/resources/application.properties
Added filter to retrieve events only in status COMPLETED or DELETED
> Added filter to events to get only onbordings in COMPLETED or DELETED

- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/mapper/OnboardingMapper.java
- apps/onboarding-cdc/src/main/resources/application.properties
Added variables to invoke notification functions after data changes on database
> [SELC-5014] feat: updated variables for terraform

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/NotificationToSend.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/CustomOffsetDateTimeSerializer.java
> [SELC - 5016] feat: added custom serializer

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
added status filter 
Support team requires this filter when retrieving membership requests for a particular institution
the microservice was started locally and the API was invoked by filtering by Status
> [SELC - 5031] feat: add filter status when getting onboarding detail

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/WorkflowType.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
Added worflow type NEW_ADMIN to manage the administrator addition flow
> [SELC-5035] feat: added new worflow type to manage the administrator addition flow

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/PartyRole.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- added enum ADMIN_EA in PartyRole
- increased sdk version from 0.1.11 to 0.1.12
This change is related to the feature of Enti Aggregatori. 
New role, ADMIN_EA, is required for Enti Aggregatori's associated products.
> [SELC-4995] feat: add PartyRole ADMIN_EA and increase sdk version

- infra/container_apps/onboarding-cdc/env/dev-pnpg/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/dev/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/prod/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/uat/terraform.tfvars
- infra/functions/onboarding-functions/functions.tf
Storing function api key to KV from terraform when create function from module
> [SELC-5033] Storing function api key to KV from terraform

- apps/onboarding-ms/pom.xml
- updated sdk version for onboarding ms
> [SELC - updatedSdkVersion] feat: updated sdk version

- infra/container_apps/onboarding-cdc/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/prod/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/uat/terraform.tfvars
- updated onboarding functions url
> [SELC - updatedOnboardingFunctionUrl ] feat: updated onboarding functions url

- .github/workflows/swagger_conflict_update_ms.yml
- apps/onboarding-ms/src/main/resources/application.properties
Using a common GitHub Action designed to facilitate the detection of conflicts in Swagger documentation files
> ops: GitHub Action to detect breaking changes on Swagger

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/WorkflowType.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
Added new workflow type to manage the users import flow
In order to manage users import flow (eventually), a new workflow type has been added
> [SELC-5035] feat: Added new workflow type to manage the users import flow

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
Move store activatedAt timestamp to new function to avoid more storage when product contains test environment.
> [SELC-5041] Refactor store activatedAt

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- add "support" tag to /{onboardingId}/consume
- add "Onboarding" tag to OnboardingController
- align openapi
Align tags for implementation of this [RFC](https://pagopa.atlassian.net/wiki/spaces/SCP/pages/edit-v2/1084883169)
> [SELC-5056] chore: added "support" and "Onboarding" tags to /{onboardingId}/consume

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/exception/InvalidRequestException.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/GenericError.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/profile/OnboardingTestProfile.java
- added new API to complete users onboarding process
- added new service to complete users onboarding
- added check to verify if referenceOnboarding had onboardingStatus to COMPLETED
This new API has been implemented as it is the final step for the conclusion of the new User Onboarding process
the microservice was started locally and the API was invoked in various conditions:
- Request with referenceOnboardingId pointing to a successful Onboarding with onboardingStatus on the same product COMPLETED
- Request with referenceOnboardingId pointing to an incorrect Onboarding with onboardingStatus on the same product !COMPLETED
- referenceOnboardingStatus null
> [SELC - 4376] feat: added new API to complete users onboarding process

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/util/QueryUtilsTest.java
Adding new endpoint to update onboarding data
This new API can assist operations when they need to modify incorrect input dates stored in the onboarding database. Managers sometimes fill out the onboarding request web form with errors, and the associated billing will be unusable until corrected.
> [SELC-5088] feat: Adding API for update some field for onboarding

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/constants/CustomError.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingUserRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/exception/InvalidRequestException.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/InstitutionMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/GenericError.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/profile/OnboardingTestProfile.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/util/QueryUtilsTest.java
> [SELC-5088] ADD API Prod from main

- apps/onboarding-functions/src/main/resources/application.properties
(cherry picked from commit b79c661f9c0cd2e968c5a9f0aa11648192f9bacd)
> fix: added missing url config for geographic taxonomies client (#308)

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/model/OnboardingGetFilters.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Added onboardingId and institutionId filters to getOnboardingWithFilter API
local env
> [SELC-4899] feat: added filters to getOnboardingWithFilter API

- apps/onboarding-cdc/pom.xml
- apps/onboarding-cdc/src/main/openapi/onboarding_functions.json
- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingBaseRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/OnboardingResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
Added isAggregator and aggregates field to:
- Onboarding (ms module)
- Onboarding (function module) 
- OnboardingBaseRequest
These fields are necessary for the new onboarding flow for aggregator institution that will be implemented to work correctly
> [SELC - 5123] feat: added new isAggregator and aggregates fields to Onboarding Objects

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/NotificationFunctions.java
> [SELC-5127] Restore notification send API

- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/docs/openapi.yaml
> chore: Upgrade quarkus version 3.11.2

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/MailTemplatePathConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- infra/functions/onboarding-functions/env/dev-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
- added new functions to send mail with contract for aggregator
- added variables to infra for template mail
this new function has been added which is triggered when an aggregator makes an onboarding request. It is similar to the classic onboarding process for an institution, but a new type of email is sent following a new workflow
the function was invoked and it was verified that the status changed from REQUEST to PENDING and that the new email was sent correctly
> [SELC - 5067] feat: added new functions to send mail with contract for aggregator

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/OnboardingAggregateOrchestratorInput.java
- Added OnboardingAggregateOrchestratorInput class
This class will be input request for new function CreateOnboardingRequest, needed to onboard aggregate
> [SELC-5143] Feat: Added OnboardingAggregateOrchestratorInput class

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/ResponseWrapper.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/NotificationFunctions.java
> [SELC-5197] Refactor notification send API using Optional ifPresentOrElse

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/StandardNotificationBuilder.java
Bug fixing, protect code if token is null
When token is null notification cannot be sent
> [SELC-5115] Allow sending notification without requiring a token

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/MailTemplatePathConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/MailTemplatePlaceholdersConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Aggregator.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
- infra/functions/onboarding-functions/env/dev-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
- added function sendCompletedEmailAggregate
- added unit tests
- add template variabile reference in properties
- add template variables in infra
> [SELC-5080] feat: added new function sendCompletedEmailAggregate

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Aggregator.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- Added function for CreateOnboardingRequest
We need a function to persist onboarding for aggregates
> [SELC-5097] Feat: Added function for CreateOnboardingRequest

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/client/fd/FDRestClient.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/OrganizationLightBeanResponse.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/OrganizationResponse.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/ExternalFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/NotificationFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CheckOrganizationServiceDefault.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/ExternalFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/NotificationFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CheckOrganizationServiceDefaultTest.java
added rest client and invocation of FD check organization api in checkOrganization function
local env
> SELC-5122: added rest client and invocation of FD check organization api

- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CheckOrganizationServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/profile/CheckOrganizationByPassTestProfile.java
- apps/onboarding-functions/src/test/resources/application.properties
Fix error in unit test for check organization
> fix: unit tests check organization

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/ProductMapper.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/openapi/user.json
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- align user openapi
- persist delegationId in createUsers
This change is required to persist delegationId to user-ms.
> [SELC-5083] feat: persist delegationId in createUsers

- apps/onboarding-functions/src/main/resources/application.properties
changed client_secret env reference
There was the wrong env reference for client_secret properties
local env
> [SELC-5122] fix: changed client_secret env reference

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/OnboardingWorkflowInstitution.java
Updated registration template path for INSTITUTION workflow
With this fix, after onboarding completion for INSTITUTION workflow, a mail with correct template (and not the one for PT) will be sent to the institution.  
I have deployed the feature branch directly in dev env
> [SELC-5149] fix: Updated registration template path for INSTITUTION workflow

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
Set isAggregator to true whe persisting an aggregator institution durign onboarding
Is Aggregator is required to know that the institution functions as an aggregator for the other institutions for the given product
> [SELC-5084] feat: map isAggregate when persisting onboarding

- apps/onboarding-cdc/pom.xml
- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/TokenType.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
added User entry in TokenType enum and updated sdk versions
local env
> feat: added User entry in TokenType enum and updated sdk versions

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/AckPayloadRequest.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/ExternalFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/AckStatus.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/ExternalFunctionsTest.java
Added function for messageAcknowledgment
local env
> [SELC-4921] feat: added function for messageAcknowledgment

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
> [SELC-5184] fix: Update path file contract

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- infra/functions/onboarding-functions/env/dev-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
> Added infra variables for confirmation token url in case of USER workflow

- apps/onboarding-functions/src/main/resources/application.properties
> fix: 404 Error on User

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorConfirmation.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorContractRegistration.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorContractRegistrationAggregator.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForApprove.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForApprovePt.java
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
Fix execution pending state for completion workflow
In order to complete onboarding, the function SEND_MAIL_COMPLETION_ACTIVITY should accept as parameter the new wrapper object OnboardingWorkflow
I have deployed the branch in dev and completed a request of onboarding (CONTRACT_REGISTRATION)
> [SELC-5149] feat: Fix execution pending state for completion workflow

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorContractRegistrationAggregator.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- add executePendingState in WorkflowExecutorContractRegistrationAggregator
> [SELC-5095] feat: executePendingState in WorkflowExecutorContractRegistrationAggregator

- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
Update env variable USER_MS_SEND_EMAIL to false in production environments
We avoid to send wrong emails in production until the new fix will be merged into main
> chore: Update env variable USER_MS_SEND_EMAIL to false in production environments

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
Fix call search institutions API
> FIX Releases 0.3.1 

- .github/workflows/release_ms.yml
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
* Using common [call_release_docker](https://github.com/pagopa/selfcare-commons/blob/main/.github/workflows/call_release_docker.yml) for uploading onboarding-ms openapi on azure storage
* Adding internal-v1 tag for openapi-merge
> chore: Using common Release openapi onboarding ms

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
> Merge back from 0.3.1

- infra/container_apps/hub_spid_login/env/dev/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/dev/terraform.tfvars
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
> chore: Move to Container App Env workload DEV

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/model/RowError.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/AggregatesServiceDefault.java
- Added cf in RowError
We need to trace cf in invalid rows of aggregates ccsv
> [SELC-5116] Fix: Added cf in RowError

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
Adding search when workflowType not exists in the db
> [SELC-5299] Fix count notification

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
Increment timeout time for start orchestration as in PNPG DEV time is more then 60 sec
> [SELC-5300] feat: Increment timeout time for start orchestration

- infra/container_apps/hub_spid_login/env/uat/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/uat/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
> chore: Move to Container App Env workload UAT

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorConfirmation.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
> [SELC-5300] Add Test email for enable pec Monitoring

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/model/RecipientCodeStatus.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- Added new API to check recipientCode
This API is used to verify that a valid recipientCode is passed.
the API was invoked and it was verified that everything was working properly
> [SELC - 5275] feat: added new API to checkRecipientCode

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtils.java
-Added check on institutionType for check recipient code
The check on recipient code should be valid only for PA
> [SELC-5276] feat: Added check on institutionType for check recipient code

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefaultTest.java
> [Hotfix] Add more log to telemetry client

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefaultTest.java
> Add more log

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
Currently on PNPG (forceCreateInstitution) does not get returned id value for update onboarding institution data.
> [SELC-5319] Retrieve Institution Id when create institution

- infra/container_apps/hub_spid_login/env/prod/terraform.tfvars
- infra/container_apps/onboarding-cdc/env/prod/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
> chore: Move to Container App Env workload PROD

- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
> chore: Set USER_MS_SEND_MAIL true in env PROD

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
Added condition to avoid sending mail in case of unavailability of external service. In the service with sender email, an env variabile has been added. If false, the code will skip the email step and the azure functions will not fail.
> Added condition to avoid sending mail in case of unavailability of external service

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
Added telemetry client to track mail events
In order to track events for emails - in case of success and failure - the email service has been wrapped into a try/catch block.
I have deployed the feature branch in DEV and tested a process of onboarding
> [SELC-5326] feat: Added telemetry client to track mail events

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorContractRegistrationAggregator.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
Changed parameter for function sendRegistrationContractMail in case of EA onboarding
Without this fix, the process of onboarding will not change his status from REQUEST to PENDING
> [SELC-5351] feat: Changed parameter for function sendRegistrationContractMail in case of EA onboarding

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
Added telemetry client to track mail events
In order to track events for emails - in case of success and failure - the email service has been wrapped into a try/catch block.
I have deployed the feature branch in DEV and tested a process of onboarding
> [SELC-5326] fix: Added telemetry for all send email methods

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- updated verifyOnboarding invocation
verifyOnboarding was migrated from the Core MS to the Onboarding MS, which is why it was necessary to readjust the code by invoking an internal method of the service and not the Core API which will be deprecated
The MS was started locally and several test cases were performed on different products and different institutions
> [SELC - 5349] feat: updated verifyOnboarding invocation

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/model/OnboardingGetFilters.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- Added subunitCode as onboarding get filter
We need to filter also with subunit code during search onboarding
> [SELC-5389] Feat: Added subunitCode as onboarding get filter

- apps/onboarding-functions/src/main/resources/application.properties
> Add rest client logging

- .github/workflows/call_release_function.yml
- .github/workflows/release_functions.yml
- apps/onboarding-functions/src/main/openapi/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
* Added step to release onboarding-functions OpenAPI docs on storage
* Add tag support on PUT onboarding//{onboardingId}/update
> [SELC-5401] docs: Enable release onboarding-functions OpenAPI docs on storage

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
> [SELC-5416] fix: RootParent getOriginId on notification

- apps/onboarding-functions/src/main/resources/application.properties
Added connection pool size for each client used during onboarding functions' process
This fix has been implemented in order to have a connection pool for clients that invoke microservices avoding eventually timeout exceptions
> Added connection pool size for each client into onboarding functions

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/InstitutionType.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
In order to allow onboarding for private institutions, a new enum type - PRV-  has been added
> [SELC-5407] feat: added institutionType PRV for private institutions

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
Removed telemetry client events in all points where a mail is sent
In case of unreacheable external email service, azure functions go in timeout and no exception is caught.
> [SELC-5397] feat: removed tracking events in case of sending emails

- apps/onboarding-cdc/pom.xml
- apps/onboarding-cdc/src/main/openapi/onboarding_functions.json
- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/openapi/core.json
- apps/onboarding-ms/src/main/openapi/onboarding_functions.json
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/InstitutionType.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- test-coverage/pom.xml
> [SELC-5407] feat: increased version of sdk into onboarding-ms

- infra/functions/onboarding-functions/functions.tf
Disabled the health check for onboarding functions to prevent the generation of false alert
This pull request disables the health check for the onboarding functions. The primary reason for this change is that the health check on Java functions using Quarkus is not supported by default. Consequently, enabling these health checks leads to ineffective alerts that do not accurately reflect the status of the functions.
> chore: Disable Health Check for Onboarding Functions

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Added condition to match PRV onboarding with workflowType CONTRACT_REGISTRATION
With the new institution type PRV, it's necessary to add if condition and match this type with worflow CONTRACT_REGISTRATION
> [SELC-5469] feat: added condition to match PRV onboarding with workflowType CONTRACT_REGISTRATION

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/client/auth/AuthenticationPropagationHeadersFactory.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/JwtSessionServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/client/auth/AuthenticationPropagationHeadersFactoryTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/JwtSessionServiceDefaultTest.java
> [SELC-5322] merge back

- infra/functions/onboarding-functions/env/dev-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
Enabling MAIL_SERVER_SSL value
> [SELC-5490] chore: Update mailserver params

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtils.java
- apps/onboarding-ms/src/main/openapi/party_registry_proxy.json
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Added check on fields for PRV and SCP onboarding
In order to evaluate fields into the request of onboarding (in case of PRV and SCP), a new method has been added. This method invokes proxy infocamere-pdnd api and check if digitalAddress and description correspond to values into request
> [SELC-5409] feat: added check on fields for PRV and SCP onboarding

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/Origin.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- test-coverage/pom.xml
Updated enum PDND-INFOCAMERE
Updated pom
> [SELC-5498] feature: updated enum into origin and updated pom

- apps/onboarding-ms/src/main/resources/application.properties
Added url for pdnd info camere api into application.properties-->
Without this property, the base url of client refers to localhost
I have deployed the feature branch in DEV and tested the onboarding for institution with type PRV
> [SELC-5409] fix: Added url for pdnd info camere api into application.properties

- apps/onboarding-ms/src/main/resources/application.properties
> [SELC-5409] fix: Update url client pdnd info camere api

- apps/onboarding-cdc/pom.xml
- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
Updated dependency sdk into apps modules
> [SELC-5499] fix: Updated dependency sdk into apps modules

- apps/onboarding-cdc/pom.xml
- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/resources/application.properties
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/Origin.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- test-coverage/pom.xml
> Merge main into releases/0.3.4

- libs/onboarding-sdk-azure-storage/pom.xml
> fix:  Tag version into pom of onboarding-sdk-azure-storage

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingPaRequest.java
added additionalInformation to OnboardingPaRequest model
there is the case in which a GSP can also be an IPA and therefore if it onboards the pagopa product the model needs to have additionalInformations model
the microservice was started locally and the correct functioning of the mapping was verified
> [SELC-5544] feat: added additionalInformation to OnboardingPaRequest model

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/GenericError.java
Fixed code smell for duplication of msg into GenericError
[Sonar Issues](https://sonarcloud.io/project/issues?cleanCodeAttributeCategories=ADAPTABLE&issueStatuses=OPEN%2CCONFIRMED&id=pagopa_selfcare-onboarding&open=AYwV3JhrUAxGLId2GhkV)
> [SELC-5537] fix: Fixed duplication of msg into GenericError

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/client/auth/AuthenticationPropagationHeadersFactory.java
Added constant Authorization into AuthenticationPropagationHeadersFactory
[SONAR ISSUE](https://sonarcloud.io/project/issues?cleanCodeAttributeCategories=ADAPTABLE&issueStatuses=OPEN%2CCONFIRMED&id=pagopa_selfcare-onboarding&open=AYtCDAvw5qwvHHWxj_ys)
> [SELC-5545] fix: Added constant Authorization into AuthenticationPropagationHeadersFactory

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/InstitutionResponse.java
changed return type from enum to string to InstitutionType
As a user of the selfcare api, I want all open-api to no longer have the institutionType as an enum but as a string
Some APIs were invoked to see if the data was returned correctly
> [SELC-5517] feat: changed return type from enum to string to InstitutionType

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/NotificationToSend.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/RootAggregator.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Aggregator.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/StandardNotificationBuilder.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/StandardNotificationBuilderTest.java
- Added RootAggregator and isAggregator in NotificationToSend for SC-Contract
We need to send to datalake also aggregator's informations
> [SELC-5444] Feat: Added RootAggregator and isAggregator in NotificationToSend for SC-Contract

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorContractRegistrationAggregator.java
Changed object given as attribute of SEND_MAIL_REGISTRATION_FOR_CONTRACT function
In order to not have parser error, a wrapper object OnboardingWorkflow has passed as attribute to the metioned function
> Fix send mail registration for contract in case of EA

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- Enabled send event for aggregator
We need to send event for SAP and Datalake also for aggregator
> [SELC-5584] Feat: Enabled send event for aggregator

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/AggregateInstitutionRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- Added user list in Aggregate institution
Every aggregator for its Aggregate can add admin users, so we have to persist them
local test
> [SELC-5474] Feat: Added user list in Aggregate institution

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/SignatureServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/ErrorMessage.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/exception/handler/ExceptionHandlerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/SignatureServiceDefaultTest.java
Fixed duplication of msg into GenericError
[Sonar issues](
https://sonarcloud.io/project/issues?open=AYwV3JhrUAxGLId2GhkV&id=pagopa_selfcare-onboarding)
> [SELC-5537] feat: Fixed duplication of msg into GenericError

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
fixed checkManager
in the response the value is returned as a string and the check condition fails. This fix is ​​temporary, a task will need to be opened in the next sprint to do a small refactor
> [SELC-5596] fix: fixed checkManager

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/AggregatesController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/NotificationController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/TokenController.java
- apps/onboarding-ms/src/main/resources/application.properties
* Added description Attribute: Each @Operation annotation now includes a description attribute that provides a detailed explanation of the endpoint's functionality, complementing the existing summary.
* Using SmallRye auto-generate Operation Id
Enhancing your API endpoints with detailed summary and description attributes not only benefits external developers but also aids internal teams in maintaining and scaling the application. Well-documented APIs facilitate smoother integrations, reduce misunderstandings, and improve overall developer experience.
> chore: Added Auto-generation operationId and Swagger description on each endpoint

- apps/onboarding-cdc/pom.xml
- apps/onboarding-cdc/src/main/openapi/onboarding_functions.json
- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- test-coverage/pom.xml
Upgrade sdk dependency version to 0.2.1
> chore: Update sdk dependency

- apps/onboarding-cdc/pom.xml
- apps/onboarding-cdc/src/main/openapi/onboarding_functions.json
- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- test-coverage/pom.xml
> chore: Update sdk dependency (#495)

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
Set operationId as exists on APIM
> chore: Set custom operationId for OnboardingController

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
> [SELC-5481] Added api for increment aggregates and fix userRole value in mapUsers of OnboardingMapper

- apps/onboarding-ms/lombok.config
Added esclusion of coverage from lombok generated code.
> [SELC-5588] feat: Added lombok config file for module onboarding-ms

- README.md
- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/OnboardingFunctionConfig.java
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/ArubaPkcs7HashSignServiceImpl.java
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/NamiralSignServiceImpl.java
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/NamirialPkcs7HashSignServiceImpl.java
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/NamirialSignService.java
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/PadesSignServiceImpl.java
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/Pkcs7HashSignService.java
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/Pkcs7HashSignServiceImpl.java
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/client/NamirialHttpClient.java
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/entity/Credentials.java
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/entity/Preferences.java
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/entity/SignRequest.java
- libs/onboarding-sdk-crypto/src/main/resources/META-INF/beans.xml
- libs/onboarding-sdk-crypto/src/main/resources/application.properties
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- test-coverage/pom.xml
- add namirial implementation
- upgrade sdk version from 0.2.1 to 0.2.2
> [SELC-5507] feat: namirial implementation in onboarding-crypto sdk

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
Adding x-legacy-api extensions avoid to check param-case standard during OpenAPI linter verification. This is a temporary solution, these endpoint must be migrated to new ones with param-case path.
> chore: add extensions x-legacy-api to legacy endpoint

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/AggregatesController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/model/AggregateAppIo.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/model/AggregatesCsv.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/model/CsvAggregateAppIo.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/model/VerifyAggregateAppIoResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/AggregatesService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/AggregatesServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/AggregatesControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapperTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/model/CsvAggregateAppIoTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/AggregatesServiceDefaultTest.java
- apps/onboarding-ms/src/test/resources/aggregates-appio.csv
- Refactor verify appIo csv to map all data retrieved from IPA
For the contract of the aggregation entities, it is necessary to include all the data of the aggregated entities, both those retrieved from IPA and those sent via CSV and not overwritten by IPA. Therefore, it is essential that all this data is available during the initial persistence.
> [SELC-5667] Feat: Refactor verify appIo csv to map all data retrieved from IPA

- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/client/EventhubSasTokenAuthorizationTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/ExternalFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/repository/TokenRepositoryTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CheckOrganizationServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/NotificationBuilderFactoryTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/QueueEventExaminerTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/SapNotificationBuilderTest.java
Cleaning up the test classes
[SELC-5653](https://pagopa.atlassian.net/browse/SELC-5653)
[SELC-5653]: https://pagopa.atlassian.net/browse/SELC-5653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-5653] feat: Cleaning up the test classes onboarding-functions 

- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/service/ProductServiceCacheableTest.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/service/ProductServiceDefaultTest.java
Cleaning up the test classes
[SELC-5657](https://pagopa.atlassian.net/browse/SELC-5657)
[SELC-5657]: https://pagopa.atlassian.net/browse/SELC-5657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-5657] feat: Cleaning up the test classes onboarding-sdk-product

- libs/onboarding-sdk-crypto/src/test/java/it/pagopa/selfcare/onboarding/crypto/PadesSignServiceTest.java
- libs/onboarding-sdk-crypto/src/test/java/it/pagopa/selfcare/onboarding/crypto/Pkcs7HashSignServiceTest.java
Cleaning up the test classes
[SELC-5656](https://pagopa.atlassian.net/browse/SELC-5656)
[SELC-5656]: https://pagopa.atlassian.net/browse/SELC-5656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-5656] feat: Cleaning up the test classes onboarding-sdk-crypto

- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/AggregatesControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/TokenControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/exception/handler/ExceptionHandlerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/AggregatesServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/strategy/ConfigMapAllowedListOnboardingValidationStrategyTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/util/OnboardingUtilsTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/util/QueryUtilsTest.java
Cleaning up the test classes
[SELC-5655](https://pagopa.atlassian.net/browse/SELC-5655)
[SELC-5655]: https://pagopa.atlassian.net/browse/SELC-5655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-5655] feat: Cleaning up the test classes onboarding-ms

- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/entity/AggregateInstitution.java
- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/entity/Aggregator.java
- apps/onboarding-cdc/src/main/java/it/pagopa/selfcare/onboarding/event/entity/Onboarding.java
- apps/onboarding-cdc/src/main/openapi/onboarding_functions.json
- Updated onboarding object with the attribute **aggregator**
- Updated the api-doc in order to use this new attribute into Notification functions
In order to publish the aggregator's data on SC-Contracts queue, a new attribute has been added into onboarding object.
I have deployed the feature branch in DEV. Then I have completed an onboarding for EA and checked the message published on SC-Ccontracts
> [SELC-5690] fix: updated onboarding object with the attribute aggregator

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/AggregateInstitutionRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- Added aggregates field to persist on Onboarding
For the contract of the aggregation entities, it is necessary to include all the data of the aggregated entities, both those retrieved from IPA and those sent via CSV and not overwritten by IPA. Therefore, it is essential that all this data is available during the initial persistence.
> [SELC-5691] Feat: Added aggregates field to persist on Onboarding

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/config/AzureStorageConfig.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- implement create aggregates csv function
It was tested by calling CREATE_AGGREGATES_CSV_ACTIVITY function locally
> [SELC-5559] feat: implement create aggregates csv function

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/CsvService.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/AggregatesServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/CsvServiceTest.java
- apps/onboarding-ms/src/test/resources/test-read.csv
- Added check to clean blank row and skip note row
The example CSV files contain several empty rows and a 'notes' row. During compilation, these rows might not be removed, so we need to manually delete them if they are present.
> [SELC-5708] Feat: Added check to clean blank row and skip note row

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/utils/ProductUtils.java
- test-coverage/pom.xml
> [SELC-5629] fix: handle institutionType null on validRoles

- README.md
[SELC-5601](https://pagopa.atlassian.net/browse/SELC-5601)
[SELC-5601]: https://pagopa.atlassian.net/browse/SELC-5601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-5602] feat: Added setup google-java-format

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- populate aggregates csv placeholder for prod-pagopa in PRV contract
> [SELC-5736] feat: populate aggregates csv placeholder for prod-pagopa in PRV contract

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- add legal sentence at the end of aggregates csv for IO
> [SELC-5763] feat: update aggregates csv creation for IO

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- replace accents with apostrophes
- add a blank line before the legal sentence
> [SELC-5763] fix: modify legal sentence for IO at the end of aggregates csv

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- Removed postProcessor method
- Moved function to reject onboardings into executePendingState
- Updated query to exclude current onboarding from ones interested by changes
- Updated unit tests
These updates were due to some failures into orchestration function
> Removed post processor method and moved function to reject onboardings into executePendingState

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- change link text for csv aggregates for IO (from "Dati di Enti Aggregati" to "Template_Dati di Enti Aggregati_AppIO"
> [SELC-5764] feat: modify link text for csv aggregates for IO

- apps/onboarding-ms/README.md
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/openapi/user.json
- apps/onboarding-ms/src/main/resources/application.properties
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
added user apis and implementation of onboardingUserPg method
This method implements the logic required to persist new onboarding which on azure function will execute the addition of the new Manager and the deletion of inactive managers of the PG
local env
> [PNPG-244] feat: added user apis and implementation of onboardingUserPg method

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingUserPgRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
Added controller method for API onboarding/users/pg-from-ic-and-ade
> [PNPG-244] feat: added API onboarding/users/pg-from-ic-and-ade

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
Cherry pick of commit 637a05e252602b960d05ee8e6b34085fba35b47b
> Removed post processor method and added reject onboarding fn into executePendingState

- apps/onboarding-ms/README.md
- apps/onboarding-ms/src/main/resources/application.properties
- infra/container_apps/onboarding-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
> [PNPG-244] feat: added env for MS_USER_URL

- apps/onboarding-ms/src/main/resources/application.properties
added Authentication header propagation for selfcare-user clients
> [PNPG-244] feat: added Authentication header propagation for selfcare-user clients

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/CheckManagerResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
changed check-manager api to control if manager is active on selfcare-user
with this control we are able to check if user is actually active and manager on given institution
local env
> [SELC-5761] feat: changed check-manager api to control if manager is active on selfcare-user

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
renamed api path to perform onboarding of users for pg
> [PNPG-244] refactor: renamed api path to perform onboarding of users for pg

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefault.java
This is a temporary workaround until ms-user(-cdc)  will start to send notification do SC-Contracts-FD topic
> [SELC-5853] Adding send user notification from onboarding for prod-fd* products

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/AggregateInstitutionRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/model/Aggregate.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/AggregatesServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/AggregatesServiceDefaultTest.java
- Added parent description for AOO and UO aggregate
For AOO and UO we have to persist on onboarding also parent description information
> [SELC-5824] feat: Added parent description for AOO and UO aggregate

- apps/onboarding-functions/src/main/openapi/openapi.json
> [SELC-5851] Adding acknowledgment to openapi onboarding fn (#571)

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/SapNotificationBuilder.java
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/FdNotificationBuilderTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/NotificationBuilderTestUtil.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/SapNotificationBuilderTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/StandardNotificationBuilderTest.java
-Added InstitutionFromRootName in getDelegationRequest method on CompletionServiceDefault
We have to set also InstitutionFromRootName in delegate
> [SELC-5865] Feat: Added InstitutionFromRootName in getDelegationRequest 

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
Removed invocation to REJECTED_OUTDATED_ONBOARDINGS fn to avoid update on wrong records (documents with no origin or originId)
> Removed invocation to REJECTED_OUTDATED_ONBOARDINGS fn

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/client/auth/AuthenticationPropagationHeadersFactory.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
Added comments to the function CREATE_USERS_ACTIVITY in order to explain which bearer token is used to invoke the related API
> chore: added comments for send mail users fn

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- add new function to retrieve all aggregates related to an aggregator
- add unit test
> [SELC-5873] feat: add new function to retrieve all aggregates related to an aggregator

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/PaymentServiceProvider.java
Into Institution objects, the following attributes have been added:
-  providerNames;
- contractType;
- contractId;
These new fields are necessary to pass into request for the createInstitution API
> [SELC-5897] feat: Added fields for payment service provider

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForUsers.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorForUsersEa.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- add WorkflowExcecutorForUsersEa
- add new mappers
- add unit tests
This new WorkflowExcecutor is required to manage users' addition for aggegators.
> [SELC-5790] feat: add WorkflowExcecutorForUsersEa to manage USERS_EA workflow

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- add new API onboardingUsersAggregator and set workflow type to USERS_EA
This new endpoint is required to add a new onboarding of type USERS_EA to manage users addtion for aggregators
> [SELC-5788] feat: add new API onboardingUsersAggregator

- infra/container_apps/namirial-sign/container_group.tf
- infra/container_apps/namirial-sign/env/dev/terraform.tfvars
- infra/container_apps/namirial-sign/env/prod/terraform.tfvars
- infra/container_apps/namirial-sign/env/uat/terraform.tfvars
- infra/container_apps/namirial-sign/variables.tf
* Set terraform var enable_sws to true
* Refactor to handle some configuration
We want to deploy container on UAT and PROD environment
> [SELC-5509] chore: enable Namirial SWS Container on UAT and PROD

- apps/onboarding-functions/src/main/resources/application.properties
> Remove keep-alive from resteasy

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
> [SEL-5902] Update institution reqiurements migrating from enum to string

- infra/container_apps/namirial-sign/container_group.tf
- infra/container_apps/namirial-sign/data.tf
- infra/container_apps/namirial-sign/env/dev/terraform.tfvars
- infra/container_apps/namirial-sign/env/prod/terraform.tfvars
- infra/container_apps/namirial-sign/env/uat/terraform.tfvars
- infra/container_apps/namirial-sign/locals.tf
- infra/container_apps/namirial-sign/variables.tf
- infra/functions/onboarding-functions/.terraform.lock.hcl
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
- libs/onboarding-sdk-crypto/src/main/java/it/pagopa/selfcare/onboarding/crypto/client/NamirialHttpClient.java
* Using http://selc-_env_-namirial-sws-cg.westeurope.azurecontainer.io:8080 URL
* Added hardcoded boundary on signing request to SWS Namirial OnPremises
* Run Pre-commit
> [SELC-5899] feat: change Namirial SWS URL using container resource group

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
Datalake can show label Utility for this companies.
> [SELC-5922] Set institution category L37 when GSP and SELC

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/OnboardingWorkflowAggregator.java
Modified inside the workflow the correct pointing for the template and contract version
A wrong contract was displayed
DEV
> [SELC-5966] feat: Fixed contract for workflow-aggregator

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefault.java
Onboarding should not send user notification even for fideiussioni digitali
> Remove send user notification

- infra/functions/onboarding-functions/.terraform.lock.hcl
- infra/functions/onboarding-functions/env/dev-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
- infra/functions/onboarding-functions/functions.tf
- infra/functions/onboarding-functions/main.tf
- infra/functions/onboarding-functions/variables.tf
> Update infra for function

- README.md
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/InstitutionToNotify.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
> [SELC-5995] Add supportEmail to notification

- .github/workflows/call_integration_test.yml
- .github/workflows/integration_test.yml
- infra/test/.terraform.lock.hcl
- infra/test/Selfcare-Integration.postman_environment.json
- infra/test/data.tf
- infra/test/env/dev/backend.ini
- infra/test/env/dev/backend.tfvars
- infra/test/env/dev/terraform.tfvars
- infra/test/integration_test.tf
- infra/test/locals.tf
- infra/test/main.tf
- infra/test/terraform.sh
- infra/test/variables.tf
- test/locals.tf
- test/newman/Selfcare-Integration.postman_collection.json
> [SELC-5980] Adding integration test

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/InstitutionUtils.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/InstitutionUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/util/InstitutionUtilsTest.java
Improved logic in the utility method that did not show the template path correctly
Wrong institution type when is not null
> [SELC-5812] feat: Fixed contract path for institution type

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingImportRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Currently, onboarding processes at UO Institutions do not store billing data.
> [SELC-6022] Store billing when onboarding an UO Institution

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/InstitutionUtilsTest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/InstitutionUtils.java
Fixed condition into InstitutionUtils
Added new fields into map for PSP template
Inability to make a checkbox dynamic
> [SELC-5807] feat: Added fields for PSP template

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- add parentDescription field in AggregateInstitution
This change is required to propagate parentDescription field in aggregates' onboarding
It was tested locally by invocking onboarding functions
> [SELC-6058] fix: propagate parentDescription in aggregates' onboarding

- apps/onboarding-cdc/src/main/openapi/onboarding_functions.json
- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/openapi/core.json
- apps/onboarding-ms/src/main/openapi/onboarding_functions.json
- apps/pom.xml
- test-coverage/pom.xml
> [SELC-5607] feat: Updated dependencies for new libs

- apps/onboarding-cdc/src/main/openapi/onboarding_functions.json
- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/openapi/onboarding_functions.json
- apps/pom.xml
Added new enum FOR_APPROVE_GPU into openapi-swagger
Updated modules to sdk 0.5.1
> feat: Updated libs

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingDefaultRequest.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
Added GPUData into OnboardingData
> [SELC-5514] feat: Added GPUData into OnboardingMapper

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/OnboardingMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
> [SELC-5514] feat: Updated gpuData config

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/TokenController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/Token.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/TokenControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefaultTest.java
Added api to retrieve attachment given onboardingId
This API retrieves an attachment given onboarding's identifier and its name
I have run the feature branch locally and tested the API /tokens/{onboardingId}/attachment?name={name} through POSTMAN
> [SELC-6132] feat: added api to retrieve attachment given onboardingId

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
Added into pdf mapper for PRV value of isAggregatorCheckbox
> [SELC-6109] feat: Added aggregator value for checkbox (PRV)

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerADE.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerInfocamere.java
Adding geographicTaxonomies when creating onboarding for PNPG
> [SELC-6138] Adding geographicTaxonomies on PNPG institutions

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Token.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- Added new attribute into token object
- Removed unused method into unit tests
This new attribute has been added in order to have an unique element useful to filter the list of attachments linked to the product.
Unit test is considered enough for this task
> Added new attribute into token object

- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/OnboardingGet.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefaultTest.java
Added attachments into response object for api v1/onboarding/{onboardingId}/withUserInfo
This change is necessary to show the list of attachments into admin page.
I have deployed the feature branch in DEV and tested the api v1/onboarding/{onboardingId}/withUserInfo checking the the attribute node attachments.
> [SELC-6133] feat: added attachments into response object for api v1/onboarding/{onboardingId}/withUserInfo

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-azure-storage/src/main/java/it/pagopa/selfcare/azurestorage/AzureBlobClient.java
- libs/onboarding-sdk-azure-storage/src/main/java/it/pagopa/selfcare/azurestorage/AzureBlobClientDefault.java
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
Added a new feature where given a path the content below it is searched within the storage.
This activity is required for the bonificas script (RFC)
local - dev
> [SELC-6155] feat: Added new method into SDK Azure

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-azure-storage/src/main/java/it/pagopa/selfcare/azurestorage/AzureBlobClientDefault.java
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
Fixed log injection into method
Issued show during the action of CodeQL
> [SELC-6155] bugfix: Fixed log injection into getFiles

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- test-coverage/pom.xml
Updated sdk common version into apps
> [SELC-6159] feat: Update SDK dependency

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/BusinessData.java
Added field into GpuData to display its value into report template
This change is necessary to display this value into report for GPU institution
I have deployed the feature branch in DEV and tested the api of onboarding for GPU
> [SELC-6169] feat: added field for GPU data

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
A service for PG completion has been added that sets the status to PENDING
PGs do not need the REQUEST phase which is why this change was made
ran the MS locally and invoked the API and verified that everything was working correctly
> [SELC-6177] feat: added onboardingPgCompletion service

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-azure-storage/src/main/java/it/pagopa/selfcare/azurestorage/AzureBlobClient.java
- libs/onboarding-sdk-azure-storage/src/main/java/it/pagopa/selfcare/azurestorage/AzureBlobClientDefault.java
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
Fixed method to retrive info on blob storage
dev - local
> [SELC-6155] feature: Refactored getFiles

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/TokenController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/TokenControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefaultTest.java
Added new endpoint contract-signed
This endpoint, update the field contract_signed by the onboardingId
dev - local
> [SELC-6157] feat: Added new endpoint into TokenController

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/NotificationFunctions.java
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
> [feature/SELC-6175] Set correct status on re-send notification

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/NotificationFunctions.java
> [SELC-6175] Set correct status on re-send notification

- apps/onboarding-functions/src/main/resources/application.properties
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
- infra/test/env/dev/terraform.tfvars
> [SELC-6205] chore: Add PDND_INFOCAMERE to SAP_ALLOWED_ORIGINS

- infra/functions/onboarding-functions/env/dev-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/uat-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
Due to cost reductions app service plan will be down scaled
> [SELC-6126] Update app service plan

- apps/onboarding-functions/src/main/openapi/openapi.json
> [SELC-6243] Set productId not required to be included on external api

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/NotificationFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/SapNotificationBuilder.java
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/prod/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
- infra/test/env/dev/terraform.tfvars
> Merge back from releases/0.4.7 to main

- apps/onboarding-functions/src/main/openapi/openapi.json
Updated field required
Deleted value from tags
> [SELC-6243] feat: Fixed openapi value

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerSELC.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerSELCTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- added workflowType CONFIRMATION to customValidation
- updated unit test
The CONFIRMATION workflowType is a workflow used only by Service Management to perform manual onboarding, while also performing onboarding of SELC-type institutions the modification was necessary
the onboardingCompletion API was invoked with a SELC type entity to verify that onboarding was requested
> [SELC-6232] feat: added workflowType CONFIRMATION to customValidation

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefaultTest.java
Fix api to retrieve contract
The new api retrieves a contract linked to an onboarding considering the onboarding identifier as primary key of the document.
> Fix get contract

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/Product.java
- test-coverage/pom.xml
- add institutionAggregatorContractMappings field in Product
- add setInstitutionAggregatorContractMappings
- add getInstitutionAggregatorContractMappings
- add getInstitutionAggregatorContractTemplate
- upgrade lib pom version from 0.6.2 to 0.6.3
> [SELC-6150] feat: add institutionAggregatorContractMappings field in Product

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/OnboardingResponse.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
Added new updatedAt field 
Modified log 
Request for ServiceManagement
Changing the log because it is not displayed correctly in the console
local
> [SELC-5896] feat: Added new value into OnboardingResponse for endpoint

- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
> Removed io premium

- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
> Added io premium into ONBOARDING_ALLOWED_INSTITUTIONS_PRODUCTS

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- modify aggregate admin info setting for send by getting for each aggregate its own user info
> [SELC-6140] fix: modify aggregate admin info setting for send

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/OnboardingWorkflowUser.java
Changed email template path for null manager
In case of null manager for onboarding user, the email template path is the same as if the legal representative has not changed
> [SELC-6245] feat: changed email template path for null manager

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- test-coverage/pom.xml
Updated apps module to the new sdk version
> [SELC-6335] feat: Updated sdk

- .gitignore
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/TokenController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/response/ContractSignedReport.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/SignatureService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/SignatureServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/TokenControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefaultTest.java
Adding new API
Currently selfcare storage contains files .pdf even the correct extension is .p7m
> [SELC-6341] Adding new API for check if contractSigned file is CADES

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/repository/OnboardingRepository.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/QueryUtils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/repository/OnboardingRepositoryTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/QueryUtilsTest.java
Added check for email in case of deletion of manager
In case of deletion manager, the email sent for a new user should not contain the previous manager. So, a new check has been added in order to control, through user-ms, the existence of a manager
I have deployed the feature branch in DEV and tested the flow of new user
> [SELC-6246] fix: added check for previous manager in case of new user onboarding

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/Product.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/ProductRoleInfo.java
- added userEnable to ProductRole
- added institutionTypesAllowed to Product
- updated SDK version
> [SELC-6352] feat: added new fields to Product and updated SDK version

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-common/src/main/java/it/pagopa/selfcare/onboarding/common/ProductId.java
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- updated new sdk version
- added new productId dashboard-psp
Required to enable onboarding to the new Dashboard-PSP product
> [SELC-6418] feat: update sdk version and added new productId

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- test-coverage/pom.xml
> feat: update sdk version

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/BaseRegistryManager.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManager.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- added new logic to validate institution type
a control has been added that will allow you to validate the institutionType of an institution based on the product. Not all types of institutions can sign up for all products
Local onboarding was invoked for the dashboard-psp product with an institution type different from the PSP one
> [SELC-6354] feat: added new logic to validate institution type

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/ProductRoleInfo.java
> fix: updated enableUser to skipUserCreation

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- test-coverage/pom.xml
> feat: updated sdk dependency

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
Added check on product field enableUser before to invoke CREATE_USERS_ACTIVITY
For each product and role, a new field has been added (enableUser). If this field is set true, the function to persist user should be invoked.
> [SELC-6356] feat: added check to invoke the function CREATE_USERS_ACTIVITY

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/StandardNotificationBuilderTest.java
Fix notification builder, removing contro for workflow type
> [SELC-6492] Send PSP data for all workflow

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/ErrorMessage.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
- Added verifiy onboarding for parent product
- Added prod-dashboard-psp as allowed products to onboard
- Added unit tests for different scenarios
In case of missed onboarding for parent product, an invalid request exception is thrown in order to block the onboarding for child product
I have started the ms locally and tested the different scenarios
> [SELC-6463] feat: added check on product parent onboarding

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/StandardNotificationBuilder.java
Deprecation for value internalIstitutionID
> [SELC-6505] Add new field institutionId on notification event

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/model/OnboardingGetFilters.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- Added user identifier to the getOnboardings API
- Added productIds parameter to the getOnboardings API 
This development adds new parameters for API getOnboardings in order to retrieve them given user identifier.
I have started the ms locally and tested the API GET /onboarding with different parameters
> [SELC-6478] feat: added parameter userId for get Onboardings API

- apps/onboarding-ms/pom.xml
Added into pom dependency for cucumber custom by quarkus
local
> [SELC-6439] feat: Added cucumber dependency into MS

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Fix method check-manager (temporary match)
> Fix method check-manager 

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
> Merge back from 0.4.12

- infra/container_apps/onboarding-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
Added env JWT_BEARER_TOKEN for cucumber test
needed for the calls of the various api
> [SELC-6440] feat: Added env JWT_BEARER_TOKEN (infra)

- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
> [SELC-6356] Remove prod-fd-garantito from PROD

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/util/QueryUtils.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/util/QueryUtilsTest.java
> [SELC-6552] Update origin and originId from updateOnboarding

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/NotificationToSend.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationEventServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/StandardNotificationBuilderTest.java
> chore: Avoid error when fileName include accent char

- infra/container_apps/hub_spid_login/env/prod/terraform.tfvars
- infra/container_apps/namirial-sign/container_app.tf
- infra/container_apps/namirial-sign/data.tf
- infra/container_apps/namirial-sign/env/dev/terraform.tfvars
- infra/container_apps/namirial-sign/env/prod/terraform.tfvars
- infra/container_apps/namirial-sign/env/uat/terraform.tfvars
- infra/container_apps/namirial-sign/locals.tf
- infra/container_apps/namirial-sign/private_dns.tf
- infra/container_apps/namirial-sign/variables.tf
- infra/container_apps/onboarding-cdc/env/prod/terraform.tfvars
- infra/container_apps/onboarding-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/container_apps/onboarding-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
- infra/dashboards/monitor.tf
- infra/dashboards/variables.tf
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/uat-pnpg/terraform.tfvars
- infra/functions/onboarding-functions/env/uat/terraform.tfvars
- infra/functions/onboarding-functions/functions.tf
- infra/functions/onboarding-functions/variables.tf
- infra/integration-test/integration_test.tf
- infra/integration-test/variables.tf
> [#SELC-6324] Add Namirial Container App

- .github/workflows/release_onboarding.yml
Fix action for release all onboarding modules
> FIX release branch

- infra/functions/onboarding-functions/env/prod/terraform.tfvars
> [SELC-6326] Enable Namirial Container app in PROD

- infra/container_apps/hub_spid_login/env/dev-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/env/dev/terraform.tfvars
- infra/container_apps/hub_spid_login/env/prod-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/env/prod/terraform.tfvars
- infra/container_apps/hub_spid_login/env/uat-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/env/uat/terraform.tfvars
> [SELC-6289] feat: updated company PEC

- .github/workflows/release_onboarding.yml
> feat: updated release_onboarding.yml

- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/container_apps/onboarding-ms/env/uat/terraform.tfvars
Deleted from allowed list unused products
Products no longer used
> [SELC-6589] feat: Deleted prod-fd and prod-fd-garantito from ALLOWED_LIST

- .github/workflows/call_code_review.yml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerSELC.java
> feat: added CONTRACT_REGISTRATION_AGGREGATOR workflowType for SELC

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
Added into PdfMapper new productId prod-dashboard-psp
> [SELC-6660] feat: Added mapping for new product prod-dashboard-psp

- infra/container_apps/hub_spid_login/env/prod-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/variables.tf
Update hub-spid image version and storage name
> [SELC-6703] Fix: update configuration for hub-spid-login pnpg

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/UserInstitutionFilters.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/InstitutionFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/repository/OnboardingRepository.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/InstitutionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/UserService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/QueryUtils.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/InstitutionFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/repository/OnboardingRepositoryTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/InstitutionServiceTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/UserServiceTest.java
- Added an Azure function to delete (in ms-core) an institution given its identifier and a product id
- Added an Azure function to delete a user given its identifier and a product id
- Added http trigger to schedule a durable task that wraps the two functions mentioned above
This durable function is used to trigger the deletion of a user and institution after deleting the onboarding 
I have deployed the feature branch in dev and tested the api linked to the Http trigger
> [SELC-6598] feat: added az function to delete institution and user

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/InstitutionService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/openapi/onboarding_functions.json
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- Added API to delete onboarding given its identifier -> DELETE /onboarding/{id}
- Added business logic to invoke azure orchestrator after the update of onboarding status -> DELETED
- Added unit tests
This change is a specific request of SM
I have deployed the feature branch in DEV and tested the api DELETE /onboarding/{id}
> [SELC-6596] feat: added api to delete onboarding given its identifier

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
> fix: fixed pdfMapper condition for setUpPSPData

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/TokenController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/TokenControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefaultTest.java
Added new endpoint to perform the download of the signed contract
Modified controller for downloading unsigned contract
Centralized code for searching on azure for the contract
> [SELC-6623] feat: Added new endpoint to retrive from token contract signed path

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
Added tag for the api DELETE /onboarding/{id}
This tag is necessary to expose the api DELETE /onboarding/{id} under the set internal-v1 into APIM. In this way service management will be able to invoke it.
> [SELC-6596] fix: added tag for the api DELETE /onboarding/{id}

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
> chore: renamed operationId for delete onboarding API

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- Added updatedAt for DELETE onbarding API
- Added closedAt for DELETE onbarding API
This change is necessary to update the field after invocation of api DELETE /onboarding/{id}
I have deployed the feature branch in DEV and tested DELETE /onboarding/{id}
> Fix updated at delete onboarding

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/UserInstitutionFilters.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/InstitutionFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/utils/ActivityName.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/repository/OnboardingRepository.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/InstitutionService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/UserService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/QueryUtils.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/Utils.java
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/InstitutionFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/repository/OnboardingRepositoryTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/InstitutionServiceTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/UserServiceTest.java
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/TokenController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/InstitutionService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefault.java
- apps/onboarding-ms/src/main/openapi/onboarding_functions.json
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/TokenControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefaultTest.java
- infra/container_apps/hub_spid_login/env/prod-pnpg/terraform.tfvars
- infra/container_apps/hub_spid_login/variables.tf
> fix: update release/0.4.17

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingImportRequest.java
When an institution needs to be imported into Selfcare, sometimes it does not include users.
> [SELC-6733] Removing constraint for user on onboarding import

- apps/onboarding-functions/src/main/openapi/openapi.json
Added tag on endpoint "/api/acknowledgment/{productId}/message/{messageId}/status/{status}"
> fix: Added tag for api-group "conservazione" function

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/dto/InstitutionToNotify.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
- apps/onboarding-functions/src/main/openapi/core.json
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/StandardNotificationBuilderTest.java
- added testInstitution field to InstitutionToNotify
- updated core openapi.json
Datalake needs to know if an Institution is a test Institution or not
a queue message was required and it was verified that the field was sent correctly whether true, false or null (false)
> [SELC-6813] feat: added testInstitution field to InstitutionToNotify

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerIPA.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerIPAAoo.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerIPAGps.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/RegistryManagerIPAUo.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/mapper/InstitutionMapper.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Added method to validates aggregates data
In order to validate data of aggregates and their correspondence with proxy registry data source, a new method has been added. For each aggregate, this method verifies if data from the request match data from registry proxy throwing a bad request exception in case of mismatch.
I have run the onboarding-ms locally and tested the POST api /pa/aggregation
> [SELC-6697] feat: added validation for aggregates on registry proxy

- apps/onboarding-ms/src/test/resources/features/onboarding.feature
- apps/onboarding-ms/src/test/resources/integration_data/invalid_request_gsp_not_ipa.json
- apps/onboarding-ms/src/test/resources/integration_data/success_gsp_not_ipa_request.json
- added gsp not ipa scenario
we have to implement cucumber integration test
run local implemented scenario
> [SELC-6821] feat: added gsp not ipa scenario

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/AggregateInstitution.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- remove fields taxCodePT, descriptionPT, service, syncAsyncMode from model
- remove fields taxCodePT, descriptionPT, service, syncAsyncMode from csv
- align unit tests
> [SELC-6405] feat: remove unused fields from contract aggregates csv

- apps/onboarding-ms/src/test/resources/features/onboarding.feature
- apps/onboarding-ms/src/test/resources/integration_data/success_con_request.json
- added success onboarding CON
start cucumber test locally
> [SELC-6852] feat: added success onboarding CON

- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/steps/OnboardingStep.java
- apps/onboarding-ms/src/test/resources/features/onboarding.feature
- apps/onboarding-ms/src/test/resources/integration_data/infocamere/institution_not_into_registry_request.json
- apps/onboarding-ms/src/test/resources/integration_data/infocamere/invalid_digital_address_pg_request.json
- apps/onboarding-ms/src/test/resources/integration_data/infocamere/invalid_origin_pg_request.json
- apps/onboarding-ms/src/test/resources/integration_data/infocamere/invalid_product_pg_request.json
- apps/onboarding-ms/src/test/resources/integration_data/infocamere/invalid_tax_code_pg_request.json
- apps/onboarding-ms/src/test/resources/integration_data/infocamere/invalid_user_pg_request.json
- apps/onboarding-ms/src/test/resources/integration_data/infocamere/success_pg_request.json
- apps/onboarding-ms/src/test/resources/integration_data/products.json
> [SELC-6853] feat: added cucumber test for PNPG

- apps/onboarding-ms/src/test/resources/features/onboarding.feature
- apps/onboarding-ms/src/test/resources/integration_data/aggregator/ipa/invalid_aggregate_pa_request.json
- apps/onboarding-ms/src/test/resources/integration_data/aggregator/ipa/success_aggregation_pa_request.json
- apps/onboarding-ms/src/test/resources/integration_data/aggregator/selc/success_aggregation_gpu_request.json
- added cucumber test for aggregator
> [SELC-6854] feat: added cucumber test for aggregator

- infra/container_apps/onboarding-ms/env/prod/terraform.tfvars
Updated allowed map to new syntax
> fix: updated allowed list prod

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/TokenServiceDefault.java
Adding new custom error when contract file is not present or not valid.
> [SELC-6884] Retrieve only valid contract

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/entity/registry/client/ClientRegistryPDNDInfocamere.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/steps/IntegrationProductService.java
- apps/onboarding-ms/src/test/resources/features/onboarding.feature
- apps/onboarding-ms/src/test/resources/integration_data/pdnd_infocamere/invalid_case1_scp_request.json
- apps/onboarding-ms/src/test/resources/integration_data/pdnd_infocamere/invalid_case2_scp_request.json
- apps/onboarding-ms/src/test/resources/integration_data/pdnd_infocamere/success_scp_request.json
Fixed into exception when status code of pdnd 400 for bad-request or invalid taxCode
Added test case for SCP
local - dev
> [SELC-6844] feat: Added scenario for InstitutionType SCP

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/QueueEventExaminer.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/QueueEventExaminerTest.java
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
To select notifications type from ADD or UPDATE events, currently the check is calculated from the updatedAt timestamp differs from the createdAt timestamp.
> [SELC-7080] Update condition to identify eventType

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Onboarding.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/OnboardingWorkflow.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorImport.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutorImportAggregation.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/OnboardingFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/NotificationServiceDefaultTest.java
added new logic to send completion mail for import
in agreement with the IO backoffice there is the need to send the mass import email once the onboarding is completed
The functions were called locally and it was verified that the correct email was sent
> [SELC-7040] feat: added new logic to send completion mail for import

- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/steps/IntegrationFunctionProfile.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/steps/IntegrationOperationUtils.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/steps/OnboardingFunctionStep.java
- apps/onboarding-functions/src/test/resources/application.properties
- apps/onboarding-functions/src/test/resources/features/onboarding-fn.feature
- apps/onboarding-functions/src/test/resources/integration_data/institution/institution_example.json
- apps/onboarding-functions/src/test/resources/integration_data/onboarding/selc/failed_users_request.json
- apps/onboarding-functions/src/test/resources/integration_data/onboarding/selc/success_users_request.json
- apps/onboarding-functions/src/test/resources/mock/user-registry-api.json
- apps/onboarding-functions/src/test/resources/test-user-ms.env
Fixed init of institutions mock into db
Added scenario cases for workflow USERS
local - dev
> [SELC-6858] feat: Added scenario for USERS

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/request/OnboardingBaseRequest.java
Removed not empty constraint for onboarding request aggregator
> Removed not empty constraint for onboarding request aggregator

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefaultTest.java
> fix: fixed onboarding aggregator increment

- apps/onboarding-functions/src/test/resources/integration_data/onboarding/selc/success_for_approve_gpu_request.json
1. added description for send mail to user
> [SELC-7141] feat: added description for send mail to user

- .github/workflows/call_code_review_resources_infra.yml
- .github/workflows/call_release_resources_infra.yml
- .github/workflows/pr_resources_infra.yml
- .github/workflows/release_infra_resources.yml
- .github/workflows/release_integration_test_infra.yml
- apps/onboarding-functions/src/main/resources/application.properties
- apps/onboarding-ms/src/main/resources/application.properties
- infra/container_apps/onboarding-ms/env/dev/terraform.tfvars
- infra/functions/onboarding-functions/env/dev/terraform.tfvars
- infra/integration-test/integration_test.tf
- infra/resources/_modules/storage_accounts/locals.tf
- infra/resources/_modules/storage_accounts/storage_account.tf
- infra/resources/_modules/storage_accounts/storage_containers.tf
- infra/resources/_modules/storage_accounts/variables.tf
- infra/resources/dev/data.tf
- infra/resources/dev/locals.tf
- infra/resources/dev/storage_documents.tf
> [SELC-7212] Update gha

- infra/resources/uat/.terraform.lock.hcl
- infra/resources/uat/locals.tf
- infra/resources/uat/storage_documents.tf
> [SELC-7212] Update infra for documents storage

- infra/container_apps/hub_spid_login/env/prod/terraform.tfvars
- infra/resources/_modules/storage_accounts/storage_account.tf
- infra/resources/_modules/storage_accounts/storage_containers.tf
- infra/resources/dev/locals.tf
- infra/resources/dev/storage_documents.tf
- infra/resources/prod/locals.tf
- infra/resources/prod/main.tf
- infra/resources/prod/storage_documents.tf
- infra/resources/uat/.terraform.lock.hcl
- infra/resources/uat/locals.tf
- infra/resources/uat/main.tf
- infra/resources/uat/storage_documents.tf
> [SELC-7212] Update infra resources

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/SignatureServiceDefault.java
> fix: updated digest check

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/functions/TokenFunctions.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractService.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/functions/TokenFunctionsTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- infra/resources/dev/storage_documents.tf
- infra/resources/prod/storage_documents.tf
- infra/resources/uat/storage_documents.tf
Delete all files included in onboarding process
> [SELC-7212] Update deleteOnboarding function

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/pom.xml
- test-coverage/pom.xml
> Update libs sdk

- apps/onboarding-functions/pom.xml
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceTest.java
- updated dss library according to standard
- updated openhtmltopdf-svg-support library
- added pdfbox library
The dss library has been updated to comply with standards. A patched version of the openhtmltopdf-svg-support library was used because the latest official version had a vulnerability. Finally, the pdfbox library was added to release 2 to resolve an incompatibility issue with the new dss version of the fonts used when creating the contract PDF.
It was verified that the tests did not break and the functions that affected the code changes were called.
> feat: updated dss library according to standard

- .github/workflows/cucumber_function_integration_test.yml
Fixed base path of module
Added logout of az session
> Fixed integration-test action for onboarding-fn

- .github/workflows/cucumber_function_integration_test.yml
Added stage to upload report of cucumber test
> fix: Added report stage into action for functions

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/entity/Payment.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/PdfMapper.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/service/ContractServiceDefaultTest.java
Added new fields from payment obj
local - dev
> [SELC-7435] feat: Added fields to pdf mapper for prod-idpay-merchant

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/service/CompletionServiceDefault.java
- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/workflow/WorkflowExecutor.java
- updated store onboarding activatedAt logic
> fix: updated store onboarding activatedAt logic

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/Product.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductService.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceCacheable.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceDefault.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/service/ProductServiceDefaultTest.java
Added logic to onboard by taxCode set into configuration file
> [SELC-7612] feat: Added allowedInstitutionByTaxCode into sdk

- apps/onboarding-functions/src/main/java/it/pagopa/selfcare/onboarding/utils/BaseNotificationBuilder.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/NotificationBuilderTestUtil.java
- apps/onboarding-functions/src/test/java/it/pagopa/selfcare/onboarding/utils/StandardNotificationBuilderTest.java
- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingService.java
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
- added sole trader boolean for verifyOnboarding
- refactor verifyOnboarding logic
With the onboarding of sole trader in the verify onboarding phase, since taxCode and originId are used to perform the search on the DB, then this data must be encrypted to perform the search, the discriminant is this Boolean sole trader, as it was for the onboarding
the api was invoked to cover the various test cases
> feat: updated verify onboarding logic for sole trader

- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefault.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/service/OnboardingServiceDefaultTest.java
Added new validation by institutionTaxCode
> [SELC-7664] feat: Added new implementation for validation by institutionTaxCode

- libs/onboarding-sdk-azure-storage/pom.xml
- libs/onboarding-sdk-common/pom.xml
- libs/onboarding-sdk-crypto/pom.xml
- libs/onboarding-sdk-pom/pom.xml
- libs/onboarding-sdk-product/pom.xml
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/entity/Product.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductService.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceCacheable.java
- libs/onboarding-sdk-product/src/main/java/it/pagopa/selfcare/product/service/ProductServiceDefault.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/service/ProductServiceCacheableTest.java
- libs/onboarding-sdk-product/src/test/java/it/pagopa/selfcare/product/service/ProductServiceDefaultTest.java
Added javadoc to missing method
Added new method to return expirationDate
> [SELC-7657] feat: Added method to return expirationDate by product

- apps/onboarding-functions/pom.xml
- apps/onboarding-ms/pom.xml
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/steps/IntegrationProductService.java
- apps/pom.xml
- test-coverage/pom.xml
Updated sdk version into project
> [SELC-7692] feat: Updated sdk version

- apps/onboarding-ms/src/main/docs/openapi.json
- apps/onboarding-ms/src/main/docs/openapi.yaml
- apps/onboarding-ms/src/main/java/it/pagopa/selfcare/onboarding/controller/OnboardingController.java
- apps/onboarding-ms/src/test/java/it/pagopa/selfcare/onboarding/controller/OnboardingControllerTest.java
> feat: updated verifyOnboarding
